# coding: utf-8

"""
    lims

    LIMS web service  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from web.src.services.lims.openapi.configuration import Configuration


class MetaDataEntry(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'meta_field_name': 'str',
        'meta_field_value': 'str'
    }

    attribute_map = {
        'meta_field_name': 'metaFieldName',
        'meta_field_value': 'metaFieldValue'
    }

    def __init__(self, meta_field_name=None, meta_field_value=None, local_vars_configuration=None):  # noqa: E501
        """MetaDataEntry - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._meta_field_name = None
        self._meta_field_value = None
        self.discriminator = None

        if meta_field_name is not None:
            self.meta_field_name = meta_field_name
        if meta_field_value is not None:
            self.meta_field_value = meta_field_value

    @property
    def meta_field_name(self):
        """Gets the meta_field_name of this MetaDataEntry.  # noqa: E501


        :return: The meta_field_name of this MetaDataEntry.  # noqa: E501
        :rtype: str
        """
        return self._meta_field_name

    @meta_field_name.setter
    def meta_field_name(self, meta_field_name):
        """Sets the meta_field_name of this MetaDataEntry.


        :param meta_field_name: The meta_field_name of this MetaDataEntry.  # noqa: E501
        :type meta_field_name: str
        """

        self._meta_field_name = meta_field_name

    @property
    def meta_field_value(self):
        """Gets the meta_field_value of this MetaDataEntry.  # noqa: E501


        :return: The meta_field_value of this MetaDataEntry.  # noqa: E501
        :rtype: str
        """
        return self._meta_field_value

    @meta_field_value.setter
    def meta_field_value(self, meta_field_value):
        """Sets the meta_field_value of this MetaDataEntry.


        :param meta_field_value: The meta_field_value of this MetaDataEntry.  # noqa: E501
        :type meta_field_value: str
        """

        self._meta_field_value = meta_field_value

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MetaDataEntry):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MetaDataEntry):
            return True

        return self.to_dict() != other.to_dict()
