"""
    SAP TBR Integration

    TBR integration for SAP  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from api_clients.tbr_client.api_client import ApiClient, Endpoint
from api_clients.tbr_client.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types,
)
from api_clients.tbr_client.model.isolate import Isolate
from api_clients.tbr_client.model.isolate_update import IsolateUpdate
from api_clients.tbr_client.model.problem_details import ProblemDetails
from api_clients.tbr_client.model.row_version import RowVersion


class IsolateApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

        def __api_isolate_changed_isolates_post(self, **kwargs):
            """api_isolate_changed_isolates_post  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.api_isolate_changed_isolates_post(async_req=True)
            >>> result = thread.get()


            Keyword Args:
                row_version ([RowVersion], none_type): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                [Isolate]
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs["async_req"] = kwargs.get("async_req", False)
            kwargs["_return_http_data_only"] = kwargs.get(
                "_return_http_data_only", True
            )
            kwargs["_preload_content"] = kwargs.get("_preload_content", True)
            kwargs["_request_timeout"] = kwargs.get("_request_timeout", None)
            kwargs["_check_input_type"] = kwargs.get("_check_input_type", True)
            kwargs["_check_return_type"] = kwargs.get("_check_return_type", True)
            kwargs["_host_index"] = kwargs.get("_host_index")
            return self.call_with_http_info(**kwargs)

        self.api_isolate_changed_isolates_post = Endpoint(
            settings={
                "response_type": ([Isolate],),
                "auth": [],
                "endpoint_path": "/api/Isolate/ChangedIsolates",
                "operation_id": "api_isolate_changed_isolates_post",
                "http_method": "POST",
                "servers": None,
            },
            params_map={
                "all": [
                    "row_version",
                ],
                "required": [],
                "nullable": [
                    "row_version",
                ],
                "enum": [],
                "validation": [],
            },
            root_map={
                "validations": {},
                "allowed_values": {},
                "openapi_types": {
                    "row_version": (
                        [RowVersion],
                        none_type,
                    ),
                },
                "attribute_map": {},
                "location_map": {
                    "row_version": "body",
                },
                "collection_format_map": {},
            },
            headers_map={
                "accept": ["application/json", "application/problem+json"],
                "content_type": ["application/json"],
            },
            api_client=api_client,
            callable=__api_isolate_changed_isolates_post,
        )

        def __api_isolate_isolate_id_get(self, isolate_id, **kwargs):
            """api_isolate_isolate_id_get  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.api_isolate_isolate_id_get(isolate_id, async_req=True)
            >>> result = thread.get()

            Args:
                isolate_id (str, none_type):

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                Isolate
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs["async_req"] = kwargs.get("async_req", False)
            kwargs["_return_http_data_only"] = kwargs.get(
                "_return_http_data_only", True
            )
            kwargs["_preload_content"] = kwargs.get("_preload_content", True)
            kwargs["_request_timeout"] = kwargs.get("_request_timeout", None)
            kwargs["_check_input_type"] = kwargs.get("_check_input_type", True)
            kwargs["_check_return_type"] = kwargs.get("_check_return_type", True)
            kwargs["_host_index"] = kwargs.get("_host_index")
            kwargs["isolate_id"] = isolate_id
            return self.call_with_http_info(**kwargs)

        self.api_isolate_isolate_id_get = Endpoint(
            settings={
                "response_type": (Isolate,),
                "auth": [],
                "endpoint_path": "/api/Isolate/{isolateId}",
                "operation_id": "api_isolate_isolate_id_get",
                "http_method": "GET",
                "servers": None,
            },
            params_map={
                "all": [
                    "isolate_id",
                ],
                "required": [
                    "isolate_id",
                ],
                "nullable": [
                    "isolate_id",
                ],
                "enum": [],
                "validation": [],
            },
            root_map={
                "validations": {},
                "allowed_values": {},
                "openapi_types": {
                    "isolate_id": (
                        str,
                        none_type,
                    ),
                },
                "attribute_map": {
                    "isolate_id": "isolateId",
                },
                "location_map": {
                    "isolate_id": "path",
                },
                "collection_format_map": {},
            },
            headers_map={
                "accept": ["application/json", "application/problem+json"],
                "content_type": [],
            },
            api_client=api_client,
            callable=__api_isolate_isolate_id_get,
        )

        def __api_isolate_put(self, **kwargs):
            """api_isolate_put  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.api_isolate_put(async_req=True)
            >>> result = thread.get()


            Keyword Args:
                isolate_update (IsolateUpdate): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                bool
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs["async_req"] = kwargs.get("async_req", False)
            kwargs["_return_http_data_only"] = kwargs.get(
                "_return_http_data_only", True
            )
            kwargs["_preload_content"] = kwargs.get("_preload_content", True)
            kwargs["_request_timeout"] = kwargs.get("_request_timeout", None)
            kwargs["_check_input_type"] = kwargs.get("_check_input_type", True)
            kwargs["_check_return_type"] = kwargs.get("_check_return_type", True)
            kwargs["_host_index"] = kwargs.get("_host_index")
            return self.call_with_http_info(**kwargs)

        self.api_isolate_put = Endpoint(
            settings={
                "response_type": (bool,),
                "auth": [],
                "endpoint_path": "/api/Isolate",
                "operation_id": "api_isolate_put",
                "http_method": "PUT",
                "servers": None,
            },
            params_map={
                "all": [
                    "isolate_update",
                ],
                "required": [],
                "nullable": [],
                "enum": [],
                "validation": [],
            },
            root_map={
                "validations": {},
                "allowed_values": {},
                "openapi_types": {
                    "isolate_update": (IsolateUpdate,),
                },
                "attribute_map": {},
                "location_map": {
                    "isolate_update": "body",
                },
                "collection_format_map": {},
            },
            headers_map={
                "accept": ["application/json", "application/problem+json"],
                "content_type": ["application/json"],
            },
            api_client=api_client,
            callable=__api_isolate_put,
        )
