# coding: utf-8

# flake8: noqa

"""
    lims

    LIMS web service  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from web.src.services.lims.openapi.api_client import ApiClient

# import Configuration
from web.src.services.lims.openapi.configuration import Configuration

# import exceptions
from web.src.services.lims.openapi.exceptions import OpenApiException
from web.src.services.lims.openapi.exceptions import ApiAttributeError
from web.src.services.lims.openapi.exceptions import ApiTypeError
from web.src.services.lims.openapi.exceptions import ApiValueError
from web.src.services.lims.openapi.exceptions import ApiKeyError
from web.src.services.lims.openapi.exceptions import ApiException
