# coding: utf-8

"""
    Bio API

    REST API for controlling bioinformatic calculations

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from web.src.services.bio_api.openapi.models.status import Status
from typing import Optional, Set
from typing_extensions import Self

class HCTreeCalcGETResponse(BaseModel):
    """
    HCTreeCalcGETResponse
    """ # noqa: E501
    job_id: StrictStr
    created_at: StrictStr
    status: Status
    finished_at: Optional[StrictStr]
    dmx_job: StrictStr
    method: StrictStr
    result: Optional[StrictStr]
    __properties: ClassVar[List[str]] = ["job_id", "created_at", "status", "finished_at", "dmx_job", "method", "result"]

    @field_validator('method')
    def method_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['single', 'complete', 'average', 'weighted', 'centroid', 'median', 'ward']):
            raise ValueError("must be one of enum values ('single', 'complete', 'average', 'weighted', 'centroid', 'median', 'ward')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HCTreeCalcGETResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if finished_at (nullable) is None
        # and model_fields_set contains the field
        if self.finished_at is None and "finished_at" in self.model_fields_set:
            _dict['finished_at'] = None

        # set to None if result (nullable) is None
        # and model_fields_set contains the field
        if self.result is None and "result" in self.model_fields_set:
            _dict['result'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HCTreeCalcGETResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "job_id": obj.get("job_id"),
            "created_at": obj.get("created_at"),
            "status": obj.get("status"),
            "finished_at": obj.get("finished_at"),
            "dmx_job": obj.get("dmx_job"),
            "method": obj.get("method"),
            "result": obj.get("result")
        })
        return _obj


