# flake8: noqa

"""
    Bio API

    REST API for controlling bioinformatic calculations  # noqa: E501

    The version of the OpenAPI document: 0.2.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from web.src.services.bio_api.openapi.api_client import ApiClient

# import Configuration
from web.src.services.bio_api.openapi.configuration import Configuration

# import exceptions
from web.src.services.bio_api.openapi.exceptions import OpenApiException
from web.src.services.bio_api.openapi.exceptions import ApiAttributeError
from web.src.services.bio_api.openapi.exceptions import ApiTypeError
from web.src.services.bio_api.openapi.exceptions import ApiValueError
from web.src.services.bio_api.openapi.exceptions import ApiKeyError
from web.src.services.bio_api.openapi.exceptions import ApiException
