// tslint:disable
/**
 * SAP
 * Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { HttpMethods, QueryConfig, ResponseBody, ResponseText } from 'redux-query';
import * as runtime from '../runtime';
import {
    QueryExpression,
    QueryExpressionFromJSON,
    QueryExpressionToJSON,
} from '../models';


/**
 * Fixing a schema export bug
 */
function dummyGetRaw<T>( requestConfig: runtime.TypedQueryConfig<T, QueryExpression> = {}): QueryConfig<T> {
    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};


    const { meta = {} } = requestConfig;

    meta.authType = ['bearer'];
    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/dummy`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'GET',
            headers: headerParameters,
        },
        body: queryParameters,
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(QueryExpressionFromJSON(body), text);
    }

    return config;
}

/**
* Fixing a schema export bug
*/
export function dummyGet<T>( requestConfig?: runtime.TypedQueryConfig<T, QueryExpression>): QueryConfig<T> {
    return dummyGetRaw( requestConfig);
}

