// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { HttpMethods, QueryConfig, ResponseBody, ResponseText } from 'redux-query';
import * as runtime from '../runtime';
import {
    HealthResponse,
    HealthResponseFromJSON,
    HealthResponseToJSON,
} from '../models';


/**
 */
function healthExtLimsRaw<T>( requestConfig: runtime.TypedQueryConfig<T, HealthResponse> = {}): QueryConfig<T> {
    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};


    const { meta = {} } = requestConfig;

    meta.authType = ['bearer'];
    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/health_ext_lims`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'GET',
            headers: headerParameters,
        },
        body: queryParameters,
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(HealthResponseFromJSON(body), text);
    }

    return config;
}

/**
*/
export function healthExtLims<T>( requestConfig?: runtime.TypedQueryConfig<T, HealthResponse>): QueryConfig<T> {
    return healthExtLimsRaw( requestConfig);
}

/**
 */
function healthExtTbrRaw<T>( requestConfig: runtime.TypedQueryConfig<T, HealthResponse> = {}): QueryConfig<T> {
    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};


    const { meta = {} } = requestConfig;

    meta.authType = ['bearer'];
    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/health_ext_tbr`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'GET',
            headers: headerParameters,
        },
        body: queryParameters,
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(HealthResponseFromJSON(body), text);
    }

    return config;
}

/**
*/
export function healthExtTbr<T>( requestConfig?: runtime.TypedQueryConfig<T, HealthResponse>): QueryConfig<T> {
    return healthExtTbrRaw( requestConfig);
}

