// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { HttpMethods, QueryConfig, ResponseBody, ResponseText } from 'redux-query';
import * as runtime from '../runtime';
import {
    MicroreactUrlResponse,
    MicroreactUrlResponseFromJSON,
    MicroreactUrlResponseToJSON,
    NewMicroreactProjectRequest,
    NewMicroreactProjectRequestFromJSON,
    NewMicroreactProjectRequestToJSON,
    NewMicroreactProjectResponse,
    NewMicroreactProjectResponseFromJSON,
    NewMicroreactProjectResponseToJSON,
} from '../models';

export interface SendToMicroreactRequest {
    body: NewMicroreactProjectRequest;
}


/**
 * Get the base url to Microreact
 */
function getMicroreactUrlRaw<T>( requestConfig: runtime.TypedQueryConfig<T, MicroreactUrlResponse> = {}): QueryConfig<T> {
    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};


    const { meta = {} } = requestConfig;

    meta.authType = ['bearer'];
    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/microreact_integration/base_url`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'GET',
            headers: headerParameters,
        },
        body: queryParameters,
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(MicroreactUrlResponseFromJSON(body), text);
    }

    return config;
}

/**
* Get the base url to Microreact
*/
export function getMicroreactUrl<T>( requestConfig?: runtime.TypedQueryConfig<T, MicroreactUrlResponse>): QueryConfig<T> {
    return getMicroreactUrlRaw( requestConfig);
}

/**
 * Send to Microreact
 */
function sendToMicroreactRaw<T>(requestParameters: SendToMicroreactRequest, requestConfig: runtime.TypedQueryConfig<T, NewMicroreactProjectResponse> = {}): QueryConfig<T> {
    if (requestParameters.body === null || requestParameters.body === undefined) {
        throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling sendToMicroreact.');
    }

    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};

    headerParameters['Content-Type'] = 'application/json';


    const { meta = {} } = requestConfig;

    meta.authType = ['bearer'];
    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/microreact_integration`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'POST',
            headers: headerParameters,
        },
        body: queryParameters || NewMicroreactProjectRequestToJSON(requestParameters.body),
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(NewMicroreactProjectResponseFromJSON(body), text);
    }

    return config;
}

/**
* Send to Microreact
*/
export function sendToMicroreact<T>(requestParameters: SendToMicroreactRequest, requestConfig?: runtime.TypedQueryConfig<T, NewMicroreactProjectResponse>): QueryConfig<T> {
    return sendToMicroreactRaw(requestParameters, requestConfig);
}

