// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { HttpMethods, QueryConfig, ResponseBody, ResponseText } from 'redux-query';
import * as runtime from '../runtime';
import {
    Project,
    ProjectFromJSON,
    ProjectToJSON,
} from '../models';

export interface SetIsPrivateRequest {
    projectKey: string;
    isPrivate: boolean;
}


/**
 * Gets projects available to user
 */
function getProjectsRaw<T>( requestConfig: runtime.TypedQueryConfig<T, Array<Project>> = {}): QueryConfig<T> {
    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};


    const { meta = {} } = requestConfig;

    meta.authType = ['bearer'];
    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/projects`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'GET',
            headers: headerParameters,
        },
        body: queryParameters,
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(body.map(ProjectFromJSON), text);
    }

    return config;
}

/**
* Gets projects available to user
*/
export function getProjects<T>( requestConfig?: runtime.TypedQueryConfig<T, Array<Project>>): QueryConfig<T> {
    return getProjectsRaw( requestConfig);
}

/**
 * Sets the private value of a project
 */
function setIsPrivateRaw<T>(requestParameters: SetIsPrivateRequest, requestConfig: runtime.TypedQueryConfig<T, void> = {}): QueryConfig<T> {
    if (requestParameters.projectKey === null || requestParameters.projectKey === undefined) {
        throw new runtime.RequiredError('projectKey','Required parameter requestParameters.projectKey was null or undefined when calling setIsPrivate.');
    }

    if (requestParameters.isPrivate === null || requestParameters.isPrivate === undefined) {
        throw new runtime.RequiredError('isPrivate','Required parameter requestParameters.isPrivate was null or undefined when calling setIsPrivate.');
    }

    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};


    const { meta = {} } = requestConfig;

    meta.authType = ['bearer'];
    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/projects/{project_key}/{is_private}`.replace(`{${"project_key"}}`, encodeURIComponent(String(requestParameters.projectKey))).replace(`{${"is_private"}}`, encodeURIComponent(String(requestParameters.isPrivate))),
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'POST',
            headers: headerParameters,
        },
        body: queryParameters,
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
    }

    return config;
}

/**
* Sets the private value of a project
*/
export function setIsPrivate<T>(requestParameters: SetIsPrivateRequest, requestConfig?: runtime.TypedQueryConfig<T, void>): QueryConfig<T> {
    return setIsPrivateRaw(requestParameters, requestConfig);
}

