// tslint:disable
/**
 * SAP
 * Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalysisQuery
 */
export interface AnalysisQuery  {
    /**
     * opaque token to supply to get the next page of isolates
     * @type {string}
     * @memberof AnalysisQuery
     */
    paging_token?: string;
    /**
     * 
     * @type {number}
     * @memberof AnalysisQuery
     */
    page_size?: number;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof AnalysisQuery
     */
    filters?: { [key: string]: string; };
}

export function AnalysisQueryFromJSON(json: any): AnalysisQuery {
    return {
        'paging_token': !exists(json, 'paging_token') ? undefined : json['paging_token'],
        'page_size': !exists(json, 'page_size') ? undefined : json['page_size'],
        'filters': !exists(json, 'filters') ? undefined : json['filters'],
    };
}

export function AnalysisQueryToJSON(value?: AnalysisQuery): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'paging_token': value.paging_token,
        'page_size': value.page_size,
        'filters': value.filters,
    };
}


