// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Resistance,
    ResistanceFromJSON,
    ResistanceToJSON,
} from './';

/**
 * 
 * @export
 * @interface AnalysisResultAllOf
 */
export interface AnalysisResultAllOf  {
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    resfinder_version?: string;
    /**
     * 
     * @type {Date}
     * @memberof AnalysisResultAllOf
     */
    kma_received_date?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AnalysisResultAllOf
     */
    date_analysis_sofi?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AnalysisResultAllOf
     */
    date_approved_serotype?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AnalysisResultAllOf
     */
    date_approved_qc?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AnalysisResultAllOf
     */
    date_approved_amr?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AnalysisResultAllOf
     */
    date_approved_st?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AnalysisResultAllOf
     */
    date_approved_toxin?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AnalysisResultAllOf
     */
    date_approved_cluster?: Date;
    /**
     * 
     * @type {number}
     * @memberof AnalysisResultAllOf
     */
    qc_provided_species?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalysisResultAllOf
     */
    qc_genome1x?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalysisResultAllOf
     */
    qc_genome10x?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalysisResultAllOf
     */
    qc_gsize_diff1x10?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalysisResultAllOf
     */
    qc_avg_coverage?: number;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    qc_final?: AnalysisResultAllOfQcFinalEnum;
    /**
     * 
     * @type {number}
     * @memberof AnalysisResultAllOf
     */
    qc_num_contigs?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalysisResultAllOf
     */
    qc_ambiguous_sites?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalysisResultAllOf
     */
    qc_num_reads?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalysisResultAllOf
     */
    qc_main_sp_plus_uncl?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalysisResultAllOf
     */
    qc_unclassified_reads?: number;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    qc_db_id?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    qc_failed_tests?: string;
    /**
     * 
     * @type {number}
     * @memberof AnalysisResultAllOf
     */
    qc_cgmlst_percent?: number;
    /**
     * 
     * @type {object}
     * @memberof AnalysisResultAllOf
     */
    cgmlst_schema_salmonella?: object;
    /**
     * 
     * @type {object}
     * @memberof AnalysisResultAllOf
     */
    cgmlst_schema_ecoli?: object;
    /**
     * 
     * @type {object}
     * @memberof AnalysisResultAllOf
     */
    cgmlst_schema_campylobacter?: object;
    /**
     * 
     * @type {object}
     * @memberof AnalysisResultAllOf
     */
    cgmlst_schema_listeria?: object;
    /**
     * 
     * @type {object}
     * @memberof AnalysisResultAllOf
     */
    cgmlst_schema_klebsiella?: object;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    subspecies?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    species_final?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    st?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    pathotype?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    pathotype_final?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    sero_enterobase?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    sero_seqsero?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    sero_antigen_seqzero?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    sero_d_tartrate?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    sero_serotype_finder?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    serotype_final?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    adhesion_final?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    virulence_genes?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    toxins_final?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    infection_source?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    resistance_genes?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    amr_profile?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    comment?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    comment_cluster?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    comment_general?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    comment_supplementary?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    comment_qc?: string;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_ami?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_amp?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_azi?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_fep?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_fot?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_f_c?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_fox?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_taz?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_t_c?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_chl?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_cip?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_cli?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_col?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_dap?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_etp?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_ery?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_fus?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_gen?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_imi?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_kan?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_lzd?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_mero?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_mup?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_nal?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_pen?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_syn?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_rif?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_str?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_sul?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_tei?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_trm?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_tet?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_tia?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_tgc?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_tmp?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_van?: Resistance;
}

export function AnalysisResultAllOfFromJSON(json: any): AnalysisResultAllOf {
    return {
        'resfinder_version': !exists(json, 'resfinder_version') ? undefined : json['resfinder_version'],
        'kma_received_date': !exists(json, 'kma_received_date') ? undefined : new Date(json['kma_received_date']),
        'date_analysis_sofi': !exists(json, 'date_analysis_sofi') ? undefined : new Date(json['date_analysis_sofi']),
        'date_approved_serotype': !exists(json, 'date_approved_serotype') ? undefined : new Date(json['date_approved_serotype']),
        'date_approved_qc': !exists(json, 'date_approved_qc') ? undefined : new Date(json['date_approved_qc']),
        'date_approved_amr': !exists(json, 'date_approved_amr') ? undefined : new Date(json['date_approved_amr']),
        'date_approved_st': !exists(json, 'date_approved_st') ? undefined : new Date(json['date_approved_st']),
        'date_approved_toxin': !exists(json, 'date_approved_toxin') ? undefined : new Date(json['date_approved_toxin']),
        'date_approved_cluster': !exists(json, 'date_approved_cluster') ? undefined : new Date(json['date_approved_cluster']),
        'qc_provided_species': !exists(json, 'qc_provided_species') ? undefined : json['qc_provided_species'],
        'qc_genome1x': !exists(json, 'qc_genome1x') ? undefined : json['qc_genome1x'],
        'qc_genome10x': !exists(json, 'qc_genome10x') ? undefined : json['qc_genome10x'],
        'qc_gsize_diff1x10': !exists(json, 'qc_gsize_diff1x10') ? undefined : json['qc_gsize_diff1x10'],
        'qc_avg_coverage': !exists(json, 'qc_avg_coverage') ? undefined : json['qc_avg_coverage'],
        'qc_final': !exists(json, 'qc_final') ? undefined : json['qc_final'],
        'qc_num_contigs': !exists(json, 'qc_num_contigs') ? undefined : json['qc_num_contigs'],
        'qc_ambiguous_sites': !exists(json, 'qc_ambiguous_sites') ? undefined : json['qc_ambiguous_sites'],
        'qc_num_reads': !exists(json, 'qc_num_reads') ? undefined : json['qc_num_reads'],
        'qc_main_sp_plus_uncl': !exists(json, 'qc_main_sp_plus_uncl') ? undefined : json['qc_main_sp_plus_uncl'],
        'qc_unclassified_reads': !exists(json, 'qc_unclassified_reads') ? undefined : json['qc_unclassified_reads'],
        'qc_db_id': !exists(json, 'qc_db_id') ? undefined : json['qc_db_id'],
        'qc_failed_tests': !exists(json, 'qc_failed_tests') ? undefined : json['qc_failed_tests'],
        'qc_cgmlst_percent': !exists(json, 'qc_cgmlst_percent') ? undefined : json['qc_cgmlst_percent'],
        'cgmlst_schema_salmonella': !exists(json, 'cgmlst_schema_salmonella') ? undefined : json['cgmlst_schema_salmonella'],
        'cgmlst_schema_ecoli': !exists(json, 'cgmlst_schema_ecoli') ? undefined : json['cgmlst_schema_ecoli'],
        'cgmlst_schema_campylobacter': !exists(json, 'cgmlst_schema_campylobacter') ? undefined : json['cgmlst_schema_campylobacter'],
        'cgmlst_schema_listeria': !exists(json, 'cgmlst_schema_listeria') ? undefined : json['cgmlst_schema_listeria'],
        'cgmlst_schema_klebsiella': !exists(json, 'cgmlst_schema_klebsiella') ? undefined : json['cgmlst_schema_klebsiella'],
        'subspecies': !exists(json, 'subspecies') ? undefined : json['subspecies'],
        'species_final': !exists(json, 'species_final') ? undefined : json['species_final'],
        'st': !exists(json, 'st') ? undefined : json['st'],
        'pathotype': !exists(json, 'pathotype') ? undefined : json['pathotype'],
        'pathotype_final': !exists(json, 'pathotype_final') ? undefined : json['pathotype_final'],
        'sero_enterobase': !exists(json, 'sero_enterobase') ? undefined : json['sero_enterobase'],
        'sero_seqsero': !exists(json, 'sero_seqsero') ? undefined : json['sero_seqsero'],
        'sero_antigen_seqzero': !exists(json, 'sero_antigen_seqzero') ? undefined : json['sero_antigen_seqzero'],
        'sero_d_tartrate': !exists(json, 'sero_d_tartrate') ? undefined : json['sero_d_tartrate'],
        'sero_serotype_finder': !exists(json, 'sero_serotype_finder') ? undefined : json['sero_serotype_finder'],
        'serotype_final': !exists(json, 'serotype_final') ? undefined : json['serotype_final'],
        'adhesion_final': !exists(json, 'adhesion_final') ? undefined : json['adhesion_final'],
        'virulence_genes': !exists(json, 'virulence_genes') ? undefined : json['virulence_genes'],
        'toxins_final': !exists(json, 'toxins_final') ? undefined : json['toxins_final'],
        'infection_source': !exists(json, 'infection_source') ? undefined : json['infection_source'],
        'resistance_genes': !exists(json, 'resistance_genes') ? undefined : json['resistance_genes'],
        'amr_profile': !exists(json, 'amr_profile') ? undefined : json['amr_profile'],
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'comment_cluster': !exists(json, 'comment_cluster') ? undefined : json['comment_cluster'],
        'comment_general': !exists(json, 'comment_general') ? undefined : json['comment_general'],
        'comment_supplementary': !exists(json, 'comment_supplementary') ? undefined : json['comment_supplementary'],
        'comment_qc': !exists(json, 'comment_qc') ? undefined : json['comment_qc'],
        'amr_ami': !exists(json, 'amr_ami') ? undefined : ResistanceFromJSON(json['amr_ami']),
        'amr_amp': !exists(json, 'amr_amp') ? undefined : ResistanceFromJSON(json['amr_amp']),
        'amr_azi': !exists(json, 'amr_azi') ? undefined : ResistanceFromJSON(json['amr_azi']),
        'amr_fep': !exists(json, 'amr_fep') ? undefined : ResistanceFromJSON(json['amr_fep']),
        'amr_fot': !exists(json, 'amr_fot') ? undefined : ResistanceFromJSON(json['amr_fot']),
        'amr_f_c': !exists(json, 'amr_f_c') ? undefined : ResistanceFromJSON(json['amr_f_c']),
        'amr_fox': !exists(json, 'amr_fox') ? undefined : ResistanceFromJSON(json['amr_fox']),
        'amr_taz': !exists(json, 'amr_taz') ? undefined : ResistanceFromJSON(json['amr_taz']),
        'amr_t_c': !exists(json, 'amr_t_c') ? undefined : ResistanceFromJSON(json['amr_t_c']),
        'amr_chl': !exists(json, 'amr_chl') ? undefined : ResistanceFromJSON(json['amr_chl']),
        'amr_cip': !exists(json, 'amr_cip') ? undefined : ResistanceFromJSON(json['amr_cip']),
        'amr_cli': !exists(json, 'amr_cli') ? undefined : ResistanceFromJSON(json['amr_cli']),
        'amr_col': !exists(json, 'amr_col') ? undefined : ResistanceFromJSON(json['amr_col']),
        'amr_dap': !exists(json, 'amr_dap') ? undefined : ResistanceFromJSON(json['amr_dap']),
        'amr_etp': !exists(json, 'amr_etp') ? undefined : ResistanceFromJSON(json['amr_etp']),
        'amr_ery': !exists(json, 'amr_ery') ? undefined : ResistanceFromJSON(json['amr_ery']),
        'amr_fus': !exists(json, 'amr_fus') ? undefined : ResistanceFromJSON(json['amr_fus']),
        'amr_gen': !exists(json, 'amr_gen') ? undefined : ResistanceFromJSON(json['amr_gen']),
        'amr_imi': !exists(json, 'amr_imi') ? undefined : ResistanceFromJSON(json['amr_imi']),
        'amr_kan': !exists(json, 'amr_kan') ? undefined : ResistanceFromJSON(json['amr_kan']),
        'amr_lzd': !exists(json, 'amr_lzd') ? undefined : ResistanceFromJSON(json['amr_lzd']),
        'amr_mero': !exists(json, 'amr_mero') ? undefined : ResistanceFromJSON(json['amr_mero']),
        'amr_mup': !exists(json, 'amr_mup') ? undefined : ResistanceFromJSON(json['amr_mup']),
        'amr_nal': !exists(json, 'amr_nal') ? undefined : ResistanceFromJSON(json['amr_nal']),
        'amr_pen': !exists(json, 'amr_pen') ? undefined : ResistanceFromJSON(json['amr_pen']),
        'amr_syn': !exists(json, 'amr_syn') ? undefined : ResistanceFromJSON(json['amr_syn']),
        'amr_rif': !exists(json, 'amr_rif') ? undefined : ResistanceFromJSON(json['amr_rif']),
        'amr_str': !exists(json, 'amr_str') ? undefined : ResistanceFromJSON(json['amr_str']),
        'amr_sul': !exists(json, 'amr_sul') ? undefined : ResistanceFromJSON(json['amr_sul']),
        'amr_tei': !exists(json, 'amr_tei') ? undefined : ResistanceFromJSON(json['amr_tei']),
        'amr_trm': !exists(json, 'amr_trm') ? undefined : ResistanceFromJSON(json['amr_trm']),
        'amr_tet': !exists(json, 'amr_tet') ? undefined : ResistanceFromJSON(json['amr_tet']),
        'amr_tia': !exists(json, 'amr_tia') ? undefined : ResistanceFromJSON(json['amr_tia']),
        'amr_tgc': !exists(json, 'amr_tgc') ? undefined : ResistanceFromJSON(json['amr_tgc']),
        'amr_tmp': !exists(json, 'amr_tmp') ? undefined : ResistanceFromJSON(json['amr_tmp']),
        'amr_van': !exists(json, 'amr_van') ? undefined : ResistanceFromJSON(json['amr_van']),
    };
}

export function AnalysisResultAllOfToJSON(value?: AnalysisResultAllOf): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'resfinder_version': value.resfinder_version,
        'kma_received_date': value.kma_received_date === undefined ? undefined : value.kma_received_date.toISOString(),
        'date_analysis_sofi': value.date_analysis_sofi === undefined ? undefined : value.date_analysis_sofi.toISOString(),
        'date_approved_serotype': value.date_approved_serotype === undefined ? undefined : value.date_approved_serotype.toISOString(),
        'date_approved_qc': value.date_approved_qc === undefined ? undefined : value.date_approved_qc.toISOString(),
        'date_approved_amr': value.date_approved_amr === undefined ? undefined : value.date_approved_amr.toISOString(),
        'date_approved_st': value.date_approved_st === undefined ? undefined : value.date_approved_st.toISOString(),
        'date_approved_toxin': value.date_approved_toxin === undefined ? undefined : value.date_approved_toxin.toISOString(),
        'date_approved_cluster': value.date_approved_cluster === undefined ? undefined : value.date_approved_cluster.toISOString(),
        'qc_provided_species': value.qc_provided_species,
        'qc_genome1x': value.qc_genome1x,
        'qc_genome10x': value.qc_genome10x,
        'qc_gsize_diff1x10': value.qc_gsize_diff1x10,
        'qc_avg_coverage': value.qc_avg_coverage,
        'qc_final': value.qc_final,
        'qc_num_contigs': value.qc_num_contigs,
        'qc_ambiguous_sites': value.qc_ambiguous_sites,
        'qc_num_reads': value.qc_num_reads,
        'qc_main_sp_plus_uncl': value.qc_main_sp_plus_uncl,
        'qc_unclassified_reads': value.qc_unclassified_reads,
        'qc_db_id': value.qc_db_id,
        'qc_failed_tests': value.qc_failed_tests,
        'qc_cgmlst_percent': value.qc_cgmlst_percent,
        'cgmlst_schema_salmonella': value.cgmlst_schema_salmonella,
        'cgmlst_schema_ecoli': value.cgmlst_schema_ecoli,
        'cgmlst_schema_campylobacter': value.cgmlst_schema_campylobacter,
        'cgmlst_schema_listeria': value.cgmlst_schema_listeria,
        'cgmlst_schema_klebsiella': value.cgmlst_schema_klebsiella,
        'subspecies': value.subspecies,
        'species_final': value.species_final,
        'st': value.st,
        'pathotype': value.pathotype,
        'pathotype_final': value.pathotype_final,
        'sero_enterobase': value.sero_enterobase,
        'sero_seqsero': value.sero_seqsero,
        'sero_antigen_seqzero': value.sero_antigen_seqzero,
        'sero_d_tartrate': value.sero_d_tartrate,
        'sero_serotype_finder': value.sero_serotype_finder,
        'serotype_final': value.serotype_final,
        'adhesion_final': value.adhesion_final,
        'virulence_genes': value.virulence_genes,
        'toxins_final': value.toxins_final,
        'infection_source': value.infection_source,
        'resistance_genes': value.resistance_genes,
        'amr_profile': value.amr_profile,
        'comment': value.comment,
        'comment_cluster': value.comment_cluster,
        'comment_general': value.comment_general,
        'comment_supplementary': value.comment_supplementary,
        'comment_qc': value.comment_qc,
        'amr_ami': ResistanceToJSON(value.amr_ami),
        'amr_amp': ResistanceToJSON(value.amr_amp),
        'amr_azi': ResistanceToJSON(value.amr_azi),
        'amr_fep': ResistanceToJSON(value.amr_fep),
        'amr_fot': ResistanceToJSON(value.amr_fot),
        'amr_f_c': ResistanceToJSON(value.amr_f_c),
        'amr_fox': ResistanceToJSON(value.amr_fox),
        'amr_taz': ResistanceToJSON(value.amr_taz),
        'amr_t_c': ResistanceToJSON(value.amr_t_c),
        'amr_chl': ResistanceToJSON(value.amr_chl),
        'amr_cip': ResistanceToJSON(value.amr_cip),
        'amr_cli': ResistanceToJSON(value.amr_cli),
        'amr_col': ResistanceToJSON(value.amr_col),
        'amr_dap': ResistanceToJSON(value.amr_dap),
        'amr_etp': ResistanceToJSON(value.amr_etp),
        'amr_ery': ResistanceToJSON(value.amr_ery),
        'amr_fus': ResistanceToJSON(value.amr_fus),
        'amr_gen': ResistanceToJSON(value.amr_gen),
        'amr_imi': ResistanceToJSON(value.amr_imi),
        'amr_kan': ResistanceToJSON(value.amr_kan),
        'amr_lzd': ResistanceToJSON(value.amr_lzd),
        'amr_mero': ResistanceToJSON(value.amr_mero),
        'amr_mup': ResistanceToJSON(value.amr_mup),
        'amr_nal': ResistanceToJSON(value.amr_nal),
        'amr_pen': ResistanceToJSON(value.amr_pen),
        'amr_syn': ResistanceToJSON(value.amr_syn),
        'amr_rif': ResistanceToJSON(value.amr_rif),
        'amr_str': ResistanceToJSON(value.amr_str),
        'amr_sul': ResistanceToJSON(value.amr_sul),
        'amr_tei': ResistanceToJSON(value.amr_tei),
        'amr_trm': ResistanceToJSON(value.amr_trm),
        'amr_tet': ResistanceToJSON(value.amr_tet),
        'amr_tia': ResistanceToJSON(value.amr_tia),
        'amr_tgc': ResistanceToJSON(value.amr_tgc),
        'amr_tmp': ResistanceToJSON(value.amr_tmp),
        'amr_van': ResistanceToJSON(value.amr_van),
    };
}

/**
* @export
* @enum {string}
*/
export enum AnalysisResultAllOfQcFinalEnum {
    A = 'A',
    B = 'B',
    C = 'C'
}


