// tslint:disable
/**
 * SAP
 * Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalysisResult
 */
export interface AnalysisResult  {
    /**
     * 
     * @type {string}
     * @memberof AnalysisResult
     */
    _id: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResult
     */
    isolateId: string;
    /**
     * 
     * @type {number}
     * @memberof AnalysisResult
     */
    QC_provided_species?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalysisResult
     */
    QC_genome1x?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalysisResult
     */
    QC_genome10x?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalysisResult
     */
    QC_Gsize_diff1x10?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalysisResult
     */
    QC_Avg_coverage?: number;
}

export function AnalysisResultFromJSON(json: any): AnalysisResult {
    return {
        '_id': json['_id'],
        'isolateId': json['isolateId'],
        'QC_provided_species': !exists(json, 'QC_provided_species') ? undefined : json['QC_provided_species'],
        'QC_genome1x': !exists(json, 'QC_genome1x') ? undefined : json['QC_genome1x'],
        'QC_genome10x': !exists(json, 'QC_genome10x') ? undefined : json['QC_genome10x'],
        'QC_Gsize_diff1x10': !exists(json, 'QC_Gsize_diff1x10') ? undefined : json['QC_Gsize_diff1x10'],
        'QC_Avg_coverage': !exists(json, 'QC_Avg_coverage') ? undefined : json['QC_Avg_coverage'],
    };
}

export function AnalysisResultToJSON(value?: AnalysisResult): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        '_id': value._id,
        'isolateId': value.isolateId,
        'QC_provided_species': value.QC_provided_species,
        'QC_genome1x': value.QC_genome1x,
        'QC_genome10x': value.QC_genome10x,
        'QC_Gsize_diff1x10': value.QC_Gsize_diff1x10,
        'QC_Avg_coverage': value.QC_Avg_coverage,
    };
}


