// tslint:disable
/**
 * SAP
 * Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Resistance,
    ResistanceFromJSON,
    ResistanceToJSON,
} from './';

/**
 * 
 * @export
 * @interface AnalysisResultAllOf
 */
export interface AnalysisResultAllOf  {
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    _id: string;
    /**
     * 
     * @type {number}
     * @memberof AnalysisResultAllOf
     */
    QC_provided_species?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalysisResultAllOf
     */
    QC_genome1x?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalysisResultAllOf
     */
    QC_genome10x?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalysisResultAllOf
     */
    QC_Gsize_diff1x10?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalysisResultAllOf
     */
    QC_Avg_coverage?: number;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    QC_final?: AnalysisResultAllOfQCFinalEnum;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    subspecies?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    species_final?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    st?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    pathotype?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    pathotype_final?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    serotype?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    serotype_final?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    adhesion?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    toxins?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    FUDnr?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    resistance_genes?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    AMR_profile?: string;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_ami?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_amp?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_azi?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_fep?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_fot?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_f_c?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_fox?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_taz?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_t_c?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_chl?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_cip?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_cli?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_col?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_dap?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_etp?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_ery?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_fus?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_gen?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_imi?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_kan?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_lzd?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_mero?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_mup?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_nal?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_pen?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_syn?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_rif?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_str?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_sul?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_tei?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_trm?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_tet?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_tia?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_tgc?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_tmp?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    AMR_van?: Resistance;
}

export function AnalysisResultAllOfFromJSON(json: any): AnalysisResultAllOf {
    return {
        '_id': json['_id'],
        'QC_provided_species': !exists(json, 'QC_provided_species') ? undefined : json['QC_provided_species'],
        'QC_genome1x': !exists(json, 'QC_genome1x') ? undefined : json['QC_genome1x'],
        'QC_genome10x': !exists(json, 'QC_genome10x') ? undefined : json['QC_genome10x'],
        'QC_Gsize_diff1x10': !exists(json, 'QC_Gsize_diff1x10') ? undefined : json['QC_Gsize_diff1x10'],
        'QC_Avg_coverage': !exists(json, 'QC_Avg_coverage') ? undefined : json['QC_Avg_coverage'],
        'QC_final': !exists(json, 'QC_final') ? undefined : json['QC_final'],
        'subspecies': !exists(json, 'subspecies') ? undefined : json['subspecies'],
        'species_final': !exists(json, 'species_final') ? undefined : json['species_final'],
        'st': !exists(json, 'st') ? undefined : json['st'],
        'pathotype': !exists(json, 'pathotype') ? undefined : json['pathotype'],
        'pathotype_final': !exists(json, 'pathotype_final') ? undefined : json['pathotype_final'],
        'serotype': !exists(json, 'serotype') ? undefined : json['serotype'],
        'serotype_final': !exists(json, 'serotype_final') ? undefined : json['serotype_final'],
        'adhesion': !exists(json, 'adhesion') ? undefined : json['adhesion'],
        'toxins': !exists(json, 'toxins') ? undefined : json['toxins'],
        'FUDnr': !exists(json, 'FUDnr') ? undefined : json['FUDnr'],
        'resistance_genes': !exists(json, 'resistance_genes') ? undefined : json['resistance_genes'],
        'AMR_profile': !exists(json, 'AMR_profile') ? undefined : json['AMR_profile'],
        'AMR_ami': !exists(json, 'AMR_ami') ? undefined : ResistanceFromJSON(json['AMR_ami']),
        'AMR_amp': !exists(json, 'AMR_amp') ? undefined : ResistanceFromJSON(json['AMR_amp']),
        'AMR_azi': !exists(json, 'AMR_azi') ? undefined : ResistanceFromJSON(json['AMR_azi']),
        'AMR_fep': !exists(json, 'AMR_fep') ? undefined : ResistanceFromJSON(json['AMR_fep']),
        'AMR_fot': !exists(json, 'AMR_fot') ? undefined : ResistanceFromJSON(json['AMR_fot']),
        'AMR_f_c': !exists(json, 'AMR_f_c') ? undefined : ResistanceFromJSON(json['AMR_f_c']),
        'AMR_fox': !exists(json, 'AMR_fox') ? undefined : ResistanceFromJSON(json['AMR_fox']),
        'AMR_taz': !exists(json, 'AMR_taz') ? undefined : ResistanceFromJSON(json['AMR_taz']),
        'AMR_t_c': !exists(json, 'AMR_t_c') ? undefined : ResistanceFromJSON(json['AMR_t_c']),
        'AMR_chl': !exists(json, 'AMR_chl') ? undefined : ResistanceFromJSON(json['AMR_chl']),
        'AMR_cip': !exists(json, 'AMR_cip') ? undefined : ResistanceFromJSON(json['AMR_cip']),
        'AMR_cli': !exists(json, 'AMR_cli') ? undefined : ResistanceFromJSON(json['AMR_cli']),
        'AMR_col': !exists(json, 'AMR_col') ? undefined : ResistanceFromJSON(json['AMR_col']),
        'AMR_dap': !exists(json, 'AMR_dap') ? undefined : ResistanceFromJSON(json['AMR_dap']),
        'AMR_etp': !exists(json, 'AMR_etp') ? undefined : ResistanceFromJSON(json['AMR_etp']),
        'AMR_ery': !exists(json, 'AMR_ery') ? undefined : ResistanceFromJSON(json['AMR_ery']),
        'AMR_fus': !exists(json, 'AMR_fus') ? undefined : ResistanceFromJSON(json['AMR_fus']),
        'AMR_gen': !exists(json, 'AMR_gen') ? undefined : ResistanceFromJSON(json['AMR_gen']),
        'AMR_imi': !exists(json, 'AMR_imi') ? undefined : ResistanceFromJSON(json['AMR_imi']),
        'AMR_kan': !exists(json, 'AMR_kan') ? undefined : ResistanceFromJSON(json['AMR_kan']),
        'AMR_lzd': !exists(json, 'AMR_lzd') ? undefined : ResistanceFromJSON(json['AMR_lzd']),
        'AMR_mero': !exists(json, 'AMR_mero') ? undefined : ResistanceFromJSON(json['AMR_mero']),
        'AMR_mup': !exists(json, 'AMR_mup') ? undefined : ResistanceFromJSON(json['AMR_mup']),
        'AMR_nal': !exists(json, 'AMR_nal') ? undefined : ResistanceFromJSON(json['AMR_nal']),
        'AMR_pen': !exists(json, 'AMR_pen') ? undefined : ResistanceFromJSON(json['AMR_pen']),
        'AMR_syn': !exists(json, 'AMR_syn') ? undefined : ResistanceFromJSON(json['AMR_syn']),
        'AMR_rif': !exists(json, 'AMR_rif') ? undefined : ResistanceFromJSON(json['AMR_rif']),
        'AMR_str': !exists(json, 'AMR_str') ? undefined : ResistanceFromJSON(json['AMR_str']),
        'AMR_sul': !exists(json, 'AMR_sul') ? undefined : ResistanceFromJSON(json['AMR_sul']),
        'AMR_tei': !exists(json, 'AMR_tei') ? undefined : ResistanceFromJSON(json['AMR_tei']),
        'AMR_trm': !exists(json, 'AMR_trm') ? undefined : ResistanceFromJSON(json['AMR_trm']),
        'AMR_tet': !exists(json, 'AMR_tet') ? undefined : ResistanceFromJSON(json['AMR_tet']),
        'AMR_tia': !exists(json, 'AMR_tia') ? undefined : ResistanceFromJSON(json['AMR_tia']),
        'AMR_tgc': !exists(json, 'AMR_tgc') ? undefined : ResistanceFromJSON(json['AMR_tgc']),
        'AMR_tmp': !exists(json, 'AMR_tmp') ? undefined : ResistanceFromJSON(json['AMR_tmp']),
        'AMR_van': !exists(json, 'AMR_van') ? undefined : ResistanceFromJSON(json['AMR_van']),
    };
}

export function AnalysisResultAllOfToJSON(value?: AnalysisResultAllOf): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        '_id': value._id,
        'QC_provided_species': value.QC_provided_species,
        'QC_genome1x': value.QC_genome1x,
        'QC_genome10x': value.QC_genome10x,
        'QC_Gsize_diff1x10': value.QC_Gsize_diff1x10,
        'QC_Avg_coverage': value.QC_Avg_coverage,
        'QC_final': value.QC_final,
        'subspecies': value.subspecies,
        'species_final': value.species_final,
        'st': value.st,
        'pathotype': value.pathotype,
        'pathotype_final': value.pathotype_final,
        'serotype': value.serotype,
        'serotype_final': value.serotype_final,
        'adhesion': value.adhesion,
        'toxins': value.toxins,
        'FUDnr': value.FUDnr,
        'resistance_genes': value.resistance_genes,
        'AMR_profile': value.AMR_profile,
        'AMR_ami': ResistanceToJSON(value.AMR_ami),
        'AMR_amp': ResistanceToJSON(value.AMR_amp),
        'AMR_azi': ResistanceToJSON(value.AMR_azi),
        'AMR_fep': ResistanceToJSON(value.AMR_fep),
        'AMR_fot': ResistanceToJSON(value.AMR_fot),
        'AMR_f_c': ResistanceToJSON(value.AMR_f_c),
        'AMR_fox': ResistanceToJSON(value.AMR_fox),
        'AMR_taz': ResistanceToJSON(value.AMR_taz),
        'AMR_t_c': ResistanceToJSON(value.AMR_t_c),
        'AMR_chl': ResistanceToJSON(value.AMR_chl),
        'AMR_cip': ResistanceToJSON(value.AMR_cip),
        'AMR_cli': ResistanceToJSON(value.AMR_cli),
        'AMR_col': ResistanceToJSON(value.AMR_col),
        'AMR_dap': ResistanceToJSON(value.AMR_dap),
        'AMR_etp': ResistanceToJSON(value.AMR_etp),
        'AMR_ery': ResistanceToJSON(value.AMR_ery),
        'AMR_fus': ResistanceToJSON(value.AMR_fus),
        'AMR_gen': ResistanceToJSON(value.AMR_gen),
        'AMR_imi': ResistanceToJSON(value.AMR_imi),
        'AMR_kan': ResistanceToJSON(value.AMR_kan),
        'AMR_lzd': ResistanceToJSON(value.AMR_lzd),
        'AMR_mero': ResistanceToJSON(value.AMR_mero),
        'AMR_mup': ResistanceToJSON(value.AMR_mup),
        'AMR_nal': ResistanceToJSON(value.AMR_nal),
        'AMR_pen': ResistanceToJSON(value.AMR_pen),
        'AMR_syn': ResistanceToJSON(value.AMR_syn),
        'AMR_rif': ResistanceToJSON(value.AMR_rif),
        'AMR_str': ResistanceToJSON(value.AMR_str),
        'AMR_sul': ResistanceToJSON(value.AMR_sul),
        'AMR_tei': ResistanceToJSON(value.AMR_tei),
        'AMR_trm': ResistanceToJSON(value.AMR_trm),
        'AMR_tet': ResistanceToJSON(value.AMR_tet),
        'AMR_tia': ResistanceToJSON(value.AMR_tia),
        'AMR_tgc': ResistanceToJSON(value.AMR_tgc),
        'AMR_tmp': ResistanceToJSON(value.AMR_tmp),
        'AMR_van': ResistanceToJSON(value.AMR_van),
    };
}

/**
* @export
* @enum {string}
*/
export enum AnalysisResultAllOfQCFinalEnum {
    A = 'A',
    B = 'B',
    C = 'C'
}


