// tslint:disable
/**
 * SAP
 * Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Resistance,
    ResistanceFromJSON,
    ResistanceToJSON,
} from './';

/**
 * 
 * @export
 * @interface AnalysisResultAllOf
 */
export interface AnalysisResultAllOf  {
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    _id: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    resfinder_version?: string;
    /**
     * 
     * @type {number}
     * @memberof AnalysisResultAllOf
     */
    QC_provided_species?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalysisResultAllOf
     */
    QC_genome1x?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalysisResultAllOf
     */
    QC_genome10x?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalysisResultAllOf
     */
    QC_Gsize_diff1x10?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalysisResultAllOf
     */
    QC_Avg_coverage?: number;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    QC_final?: AnalysisResultAllOfQCFinalEnum;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    subspecies?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    species_final?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    st?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    pathotype?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    pathotype_final?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    serotype?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    serotype_final?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    adhesion?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    adhesion_final?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    toxins?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    toxins_final?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    infection_source?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    resistance_genes?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisResultAllOf
     */
    amr_profile?: string;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_ami?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_amp?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_azi?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_fep?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_fot?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_f_c?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_fox?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_taz?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_t_c?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_chl?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_cip?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_cli?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_col?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_dap?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_etp?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_ery?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_fus?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_gen?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_imi?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_kan?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_lzd?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_mero?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_mup?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_nal?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_pen?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_syn?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_rif?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_str?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_sul?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_tei?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_trm?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_tet?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_tia?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_tgc?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_tmp?: Resistance;
    /**
     * 
     * @type {Resistance}
     * @memberof AnalysisResultAllOf
     */
    amr_van?: Resistance;
}

export function AnalysisResultAllOfFromJSON(json: any): AnalysisResultAllOf {
    return {
        '_id': json['_id'],
        'resfinder_version': !exists(json, 'resfinder_version') ? undefined : json['resfinder_version'],
        'QC_provided_species': !exists(json, 'QC_provided_species') ? undefined : json['QC_provided_species'],
        'QC_genome1x': !exists(json, 'QC_genome1x') ? undefined : json['QC_genome1x'],
        'QC_genome10x': !exists(json, 'QC_genome10x') ? undefined : json['QC_genome10x'],
        'QC_Gsize_diff1x10': !exists(json, 'QC_Gsize_diff1x10') ? undefined : json['QC_Gsize_diff1x10'],
        'QC_Avg_coverage': !exists(json, 'QC_Avg_coverage') ? undefined : json['QC_Avg_coverage'],
        'QC_final': !exists(json, 'QC_final') ? undefined : json['QC_final'],
        'subspecies': !exists(json, 'subspecies') ? undefined : json['subspecies'],
        'species_final': !exists(json, 'species_final') ? undefined : json['species_final'],
        'st': !exists(json, 'st') ? undefined : json['st'],
        'pathotype': !exists(json, 'pathotype') ? undefined : json['pathotype'],
        'pathotype_final': !exists(json, 'pathotype_final') ? undefined : json['pathotype_final'],
        'serotype': !exists(json, 'serotype') ? undefined : json['serotype'],
        'serotype_final': !exists(json, 'serotype_final') ? undefined : json['serotype_final'],
        'adhesion': !exists(json, 'adhesion') ? undefined : json['adhesion'],
        'adhesion_final': !exists(json, 'adhesion_final') ? undefined : json['adhesion_final'],
        'toxins': !exists(json, 'toxins') ? undefined : json['toxins'],
        'toxins_final': !exists(json, 'toxins_final') ? undefined : json['toxins_final'],
        'infection_source': !exists(json, 'infection_source') ? undefined : json['infection_source'],
        'resistance_genes': !exists(json, 'resistance_genes') ? undefined : json['resistance_genes'],
        'amr_profile': !exists(json, 'amr_profile') ? undefined : json['amr_profile'],
        'amr_ami': !exists(json, 'amr_ami') ? undefined : ResistanceFromJSON(json['amr_ami']),
        'amr_amp': !exists(json, 'amr_amp') ? undefined : ResistanceFromJSON(json['amr_amp']),
        'amr_azi': !exists(json, 'amr_azi') ? undefined : ResistanceFromJSON(json['amr_azi']),
        'amr_fep': !exists(json, 'amr_fep') ? undefined : ResistanceFromJSON(json['amr_fep']),
        'amr_fot': !exists(json, 'amr_fot') ? undefined : ResistanceFromJSON(json['amr_fot']),
        'amr_f_c': !exists(json, 'amr_f_c') ? undefined : ResistanceFromJSON(json['amr_f_c']),
        'amr_fox': !exists(json, 'amr_fox') ? undefined : ResistanceFromJSON(json['amr_fox']),
        'amr_taz': !exists(json, 'amr_taz') ? undefined : ResistanceFromJSON(json['amr_taz']),
        'amr_t_c': !exists(json, 'amr_t_c') ? undefined : ResistanceFromJSON(json['amr_t_c']),
        'amr_chl': !exists(json, 'amr_chl') ? undefined : ResistanceFromJSON(json['amr_chl']),
        'amr_cip': !exists(json, 'amr_cip') ? undefined : ResistanceFromJSON(json['amr_cip']),
        'amr_cli': !exists(json, 'amr_cli') ? undefined : ResistanceFromJSON(json['amr_cli']),
        'amr_col': !exists(json, 'amr_col') ? undefined : ResistanceFromJSON(json['amr_col']),
        'amr_dap': !exists(json, 'amr_dap') ? undefined : ResistanceFromJSON(json['amr_dap']),
        'amr_etp': !exists(json, 'amr_etp') ? undefined : ResistanceFromJSON(json['amr_etp']),
        'amr_ery': !exists(json, 'amr_ery') ? undefined : ResistanceFromJSON(json['amr_ery']),
        'amr_fus': !exists(json, 'amr_fus') ? undefined : ResistanceFromJSON(json['amr_fus']),
        'amr_gen': !exists(json, 'amr_gen') ? undefined : ResistanceFromJSON(json['amr_gen']),
        'amr_imi': !exists(json, 'amr_imi') ? undefined : ResistanceFromJSON(json['amr_imi']),
        'amr_kan': !exists(json, 'amr_kan') ? undefined : ResistanceFromJSON(json['amr_kan']),
        'amr_lzd': !exists(json, 'amr_lzd') ? undefined : ResistanceFromJSON(json['amr_lzd']),
        'amr_mero': !exists(json, 'amr_mero') ? undefined : ResistanceFromJSON(json['amr_mero']),
        'amr_mup': !exists(json, 'amr_mup') ? undefined : ResistanceFromJSON(json['amr_mup']),
        'amr_nal': !exists(json, 'amr_nal') ? undefined : ResistanceFromJSON(json['amr_nal']),
        'amr_pen': !exists(json, 'amr_pen') ? undefined : ResistanceFromJSON(json['amr_pen']),
        'amr_syn': !exists(json, 'amr_syn') ? undefined : ResistanceFromJSON(json['amr_syn']),
        'amr_rif': !exists(json, 'amr_rif') ? undefined : ResistanceFromJSON(json['amr_rif']),
        'amr_str': !exists(json, 'amr_str') ? undefined : ResistanceFromJSON(json['amr_str']),
        'amr_sul': !exists(json, 'amr_sul') ? undefined : ResistanceFromJSON(json['amr_sul']),
        'amr_tei': !exists(json, 'amr_tei') ? undefined : ResistanceFromJSON(json['amr_tei']),
        'amr_trm': !exists(json, 'amr_trm') ? undefined : ResistanceFromJSON(json['amr_trm']),
        'amr_tet': !exists(json, 'amr_tet') ? undefined : ResistanceFromJSON(json['amr_tet']),
        'amr_tia': !exists(json, 'amr_tia') ? undefined : ResistanceFromJSON(json['amr_tia']),
        'amr_tgc': !exists(json, 'amr_tgc') ? undefined : ResistanceFromJSON(json['amr_tgc']),
        'amr_tmp': !exists(json, 'amr_tmp') ? undefined : ResistanceFromJSON(json['amr_tmp']),
        'amr_van': !exists(json, 'amr_van') ? undefined : ResistanceFromJSON(json['amr_van']),
    };
}

export function AnalysisResultAllOfToJSON(value?: AnalysisResultAllOf): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        '_id': value._id,
        'resfinder_version': value.resfinder_version,
        'QC_provided_species': value.QC_provided_species,
        'QC_genome1x': value.QC_genome1x,
        'QC_genome10x': value.QC_genome10x,
        'QC_Gsize_diff1x10': value.QC_Gsize_diff1x10,
        'QC_Avg_coverage': value.QC_Avg_coverage,
        'QC_final': value.QC_final,
        'subspecies': value.subspecies,
        'species_final': value.species_final,
        'st': value.st,
        'pathotype': value.pathotype,
        'pathotype_final': value.pathotype_final,
        'serotype': value.serotype,
        'serotype_final': value.serotype_final,
        'adhesion': value.adhesion,
        'adhesion_final': value.adhesion_final,
        'toxins': value.toxins,
        'toxins_final': value.toxins_final,
        'infection_source': value.infection_source,
        'resistance_genes': value.resistance_genes,
        'amr_profile': value.amr_profile,
        'amr_ami': ResistanceToJSON(value.amr_ami),
        'amr_amp': ResistanceToJSON(value.amr_amp),
        'amr_azi': ResistanceToJSON(value.amr_azi),
        'amr_fep': ResistanceToJSON(value.amr_fep),
        'amr_fot': ResistanceToJSON(value.amr_fot),
        'amr_f_c': ResistanceToJSON(value.amr_f_c),
        'amr_fox': ResistanceToJSON(value.amr_fox),
        'amr_taz': ResistanceToJSON(value.amr_taz),
        'amr_t_c': ResistanceToJSON(value.amr_t_c),
        'amr_chl': ResistanceToJSON(value.amr_chl),
        'amr_cip': ResistanceToJSON(value.amr_cip),
        'amr_cli': ResistanceToJSON(value.amr_cli),
        'amr_col': ResistanceToJSON(value.amr_col),
        'amr_dap': ResistanceToJSON(value.amr_dap),
        'amr_etp': ResistanceToJSON(value.amr_etp),
        'amr_ery': ResistanceToJSON(value.amr_ery),
        'amr_fus': ResistanceToJSON(value.amr_fus),
        'amr_gen': ResistanceToJSON(value.amr_gen),
        'amr_imi': ResistanceToJSON(value.amr_imi),
        'amr_kan': ResistanceToJSON(value.amr_kan),
        'amr_lzd': ResistanceToJSON(value.amr_lzd),
        'amr_mero': ResistanceToJSON(value.amr_mero),
        'amr_mup': ResistanceToJSON(value.amr_mup),
        'amr_nal': ResistanceToJSON(value.amr_nal),
        'amr_pen': ResistanceToJSON(value.amr_pen),
        'amr_syn': ResistanceToJSON(value.amr_syn),
        'amr_rif': ResistanceToJSON(value.amr_rif),
        'amr_str': ResistanceToJSON(value.amr_str),
        'amr_sul': ResistanceToJSON(value.amr_sul),
        'amr_tei': ResistanceToJSON(value.amr_tei),
        'amr_trm': ResistanceToJSON(value.amr_trm),
        'amr_tet': ResistanceToJSON(value.amr_tet),
        'amr_tia': ResistanceToJSON(value.amr_tia),
        'amr_tgc': ResistanceToJSON(value.amr_tgc),
        'amr_tmp': ResistanceToJSON(value.amr_tmp),
        'amr_van': ResistanceToJSON(value.amr_van),
    };
}

/**
* @export
* @enum {string}
*/
export enum AnalysisResultAllOfQCFinalEnum {
    A = 'A',
    B = 'B',
    C = 'C'
}


