// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalysisSorting
 */
export interface AnalysisSorting  {
    /**
     * Name of the column to sort
     * @type {string}
     * @memberof AnalysisSorting
     */
    column?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AnalysisSorting
     */
    ascending?: boolean;
}

export function AnalysisSortingFromJSON(json: any): AnalysisSorting {
    return {
        'column': !exists(json, 'column') ? undefined : json['column'],
        'ascending': !exists(json, 'ascending') ? undefined : json['ascending'],
    };
}

export function AnalysisSortingToJSON(value?: AnalysisSorting): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'column': value.column,
        'ascending': value.ascending,
    };
}


