// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AnalysisResult,
    AnalysisResultFromJSON,
    AnalysisResultToJSON,
} from './';

/**
 * 
 * @export
 * @interface AnalysisHistory
 */
export interface AnalysisHistory  {
    /**
     * 
     * @type {Array<AnalysisResult>}
     * @memberof AnalysisHistory
     */
    items?: Array<AnalysisResult>;
}

export function AnalysisHistoryFromJSON(json: any): AnalysisHistory {
    return {
        'items': !exists(json, 'items') ? undefined : (json['items'] as Array<any>).map(AnalysisResultFromJSON),
    };
}

export function AnalysisHistoryToJSON(value?: AnalysisHistory): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'items': value.items === undefined ? undefined : (value.items as Array<any>).map(AnalysisResultToJSON),
    };
}


