// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApprovalStatus,
    ApprovalStatusFromJSON,
    ApprovalStatusToJSON,
} from './';

/**
 * 
 * @export
 * @interface ApprovalRequest
 */
export interface ApprovalRequest  {
    /**
     * 
     * @type {{ [key: string]: { [key: string]: ApprovalStatus; }; }}
     * @memberof ApprovalRequest
     */
    matrix: { [key: string]: { [key: string]: ApprovalStatus; }; };
    /**
     * 
     * @type {{ [key: string]: { [key: string]: string; }; }}
     * @memberof ApprovalRequest
     */
    required_values?: { [key: string]: { [key: string]: string; }; };
}

export function ApprovalRequestFromJSON(json: any): ApprovalRequest {
    return {
        'matrix': json['matrix'],
        'required_values': !exists(json, 'required_values') ? undefined : json['required_values'],
    };
}

export function ApprovalRequestToJSON(value?: ApprovalRequest): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'matrix': value.matrix,
        'required_values': value.required_values,
    };
}


