// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApprovalStatus,
    ApprovalStatusFromJSON,
    ApprovalStatusToJSON,
} from './';

/**
 * 
 * @export
 * @interface ApprovalAllOf
 */
export interface ApprovalAllOf  {
    /**
     * 
     * @type {string}
     * @memberof ApprovalAllOf
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ApprovalAllOf
     */
    approver?: string;
    /**
     * 
     * @type {Date}
     * @memberof ApprovalAllOf
     */
    timestamp?: Date;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: ApprovalStatus; }; }}
     * @memberof ApprovalAllOf
     */
    matrix?: { [key: string]: { [key: string]: ApprovalStatus; }; };
    /**
     * 
     * @type {Array<string>}
     * @memberof ApprovalAllOf
     */
    sequence_ids?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ApprovalAllOf
     */
    status?: ApprovalAllOfStatusEnum;
}

export function ApprovalAllOfFromJSON(json: any): ApprovalAllOf {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'approver': !exists(json, 'approver') ? undefined : json['approver'],
        'timestamp': !exists(json, 'timestamp') ? undefined : new Date(json['timestamp']),
        'matrix': !exists(json, 'matrix') ? undefined : json['matrix'],
        'sequence_ids': !exists(json, 'sequence_ids') ? undefined : json['sequence_ids'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function ApprovalAllOfToJSON(value?: ApprovalAllOf): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'approver': value.approver,
        'timestamp': value.timestamp === undefined ? undefined : value.timestamp.toISOString(),
        'matrix': value.matrix,
        'sequence_ids': value.sequence_ids,
        'status': value.status,
    };
}

/**
* @export
* @enum {string}
*/
export enum ApprovalAllOfStatusEnum {
    pending = 'pending',
    cancelled = 'cancelled',
    submitted = 'submitted'
}


