// tslint:disable
/**
 * SAP
 * Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ApprovalRequest,
    ApprovalRequestFromJSON,
    ApprovalRequestToJSON,
} from './';

/**
 * @type Approval
 * @export
 */
export interface Approval extends ApprovalRequest {
}

export function ApprovalFromJSON(json: any): Approval {
    return {
        ...ApprovalRequestFromJSON(json),
    };
}

export function ApprovalToJSON(value?: Approval): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        ...ApprovalRequestToJSON(value),
    };
}
