// tslint:disable
/**
 * SAP
 * Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Organization,
    OrganizationFromJSON,
    OrganizationToJSON,
} from './';

/**
 * 
 * @export
 * @interface BaseMetadata
 */
export interface BaseMetadata  {
    /**
     * 
     * @type {string}
     * @memberof BaseMetadata
     */
    isolate_id: string;
    /**
     * 
     * @type {string}
     * @memberof BaseMetadata
     */
    sequence_id: string;
    /**
     * 
     * @type {string}
     * @memberof BaseMetadata
     */
    sequence_filename: string;
    /**
     * 
     * @type {Organization}
     * @memberof BaseMetadata
     */
    institution: Organization;
    /**
     * 
     * @type {number}
     * @memberof BaseMetadata
     */
    project_number?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseMetadata
     */
    project_title?: string;
    /**
     * 
     * @type {Date}
     * @memberof BaseMetadata
     */
    sampling_date?: Date;
    /**
     * 
     * @type {Date}
     * @memberof BaseMetadata
     */
    received_date: Date;
    /**
     * 
     * @type {string}
     * @memberof BaseMetadata
     */
    run_id: string;
    /**
     * 
     * @type {string}
     * @memberof BaseMetadata
     */
    _public?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseMetadata
     */
    provided_species: string;
    /**
     * 
     * @type {string}
     * @memberof BaseMetadata
     */
    primary_isolate: string;
    /**
     * 
     * @type {string}
     * @memberof BaseMetadata
     */
    fud_number?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseMetadata
     */
    cluster_id?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseMetadata
     */
    epi_export?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseMetadata
     */
    resfinder_version: string;
}

export function BaseMetadataFromJSON(json: any): BaseMetadata {
    return {
        'isolate_id': json['isolate_id'],
        'sequence_id': json['sequence_id'],
        'sequence_filename': json['sequence_filename'],
        'institution': OrganizationFromJSON(json['institution']),
        'project_number': !exists(json, 'project_number') ? undefined : json['project_number'],
        'project_title': !exists(json, 'project_title') ? undefined : json['project_title'],
        'sampling_date': !exists(json, 'sampling_date') ? undefined : new Date(json['sampling_date']),
        'received_date': new Date(json['received_date']),
        'run_id': json['run_id'],
        '_public': !exists(json, 'public') ? undefined : json['public'],
        'provided_species': json['provided_species'],
        'primary_isolate': json['primary_isolate'],
        'fud_number': !exists(json, 'fud_number') ? undefined : json['fud_number'],
        'cluster_id': !exists(json, 'cluster_id') ? undefined : json['cluster_id'],
        'epi_export': !exists(json, 'epi_export') ? undefined : json['epi_export'],
        'resfinder_version': json['resfinder_version'],
    };
}

export function BaseMetadataToJSON(value?: BaseMetadata): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'isolate_id': value.isolate_id,
        'sequence_id': value.sequence_id,
        'sequence_filename': value.sequence_filename,
        'institution': OrganizationToJSON(value.institution),
        'project_number': value.project_number,
        'project_title': value.project_title,
        'sampling_date': value.sampling_date === undefined ? undefined : value.sampling_date.toISOString(),
        'received_date': value.received_date.toISOString(),
        'run_id': value.run_id,
        'public': value._public,
        'provided_species': value.provided_species,
        'primary_isolate': value.primary_isolate,
        'fud_number': value.fud_number,
        'cluster_id': value.cluster_id,
        'epi_export': value.epi_export,
        'resfinder_version': value.resfinder_version,
    };
}


