// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BioApiStatus,
    BioApiStatusFromJSON,
    BioApiStatusToJSON,
} from './';

/**
 * 
 * @export
 * @interface BioApiJobResponse
 */
export interface BioApiJobResponse  {
    /**
     * 
     * @type {string}
     * @memberof BioApiJobResponse
     */
    job_id?: string;
    /**
     * 
     * @type {string}
     * @memberof BioApiJobResponse
     */
    created_at?: string;
    /**
     * 
     * @type {BioApiStatus}
     * @memberof BioApiJobResponse
     */
    status?: BioApiStatus;
}

export function BioApiJobResponseFromJSON(json: any): BioApiJobResponse {
    return {
        'job_id': !exists(json, 'job_id') ? undefined : json['job_id'],
        'created_at': !exists(json, 'created_at') ? undefined : json['created_at'],
        'status': !exists(json, 'status') ? undefined : BioApiStatusFromJSON(json['status']),
    };
}

export function BioApiJobResponseToJSON(value?: BioApiJobResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'job_id': value.job_id,
        'created_at': value.created_at,
        'status': BioApiStatusToJSON(value.status),
    };
}


