// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BioApiStatus,
    BioApiStatusFromJSON,
    BioApiStatusToJSON,
} from './';

/**
 * 
 * @export
 * @interface BioApiJobResponse
 */
export interface BioApiJobResponse  {
    /**
     * 
     * @type {string}
     * @memberof BioApiJobResponse
     */
    jobId?: string;
    /**
     * 
     * @type {string}
     * @memberof BioApiJobResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {BioApiStatus}
     * @memberof BioApiJobResponse
     */
    status?: BioApiStatus;
}

export function BioApiJobResponseFromJSON(json: any): BioApiJobResponse {
    return {
        'jobId': !exists(json, 'jobId') ? undefined : json['jobId'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'status': !exists(json, 'status') ? undefined : BioApiStatusFromJSON(json['status']),
    };
}

export function BioApiJobResponseToJSON(value?: BioApiJobResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'jobId': value.jobId,
        'createdAt': value.createdAt,
        'status': BioApiStatusToJSON(value.status),
    };
}


