// tslint:disable
/**
 * SAP
 * Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Column
 */
export interface Column  {
    /**
     * 
     * @type {boolean}
     * @memberof Column
     */
    approvable?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Column
     */
    editable?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Column
     */
    pii?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Column
     */
    organization?: string;
    /**
     * 
     * @type {string}
     * @memberof Column
     */
    fieldName?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Column
     */
    approvesWith?: Array<string>;
}

export function ColumnFromJSON(json: any): Column {
    return {
        'approvable': !exists(json, 'approvable') ? undefined : json['approvable'],
        'editable': !exists(json, 'editable') ? undefined : json['editable'],
        'pii': !exists(json, 'pii') ? undefined : json['pii'],
        'organization': !exists(json, 'organization') ? undefined : json['organization'],
        'fieldName': !exists(json, 'field_name') ? undefined : json['field_name'],
        'approvesWith': !exists(json, 'approves_with') ? undefined : json['approves_with'],
    };
}

export function ColumnToJSON(value?: Column): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'approvable': value.approvable,
        'editable': value.editable,
        'pii': value.pii,
        'organization': value.organization,
        'field_name': value.fieldName,
        'approves_with': value.approvesWith,
    };
}


