// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWorkspace
 */
export interface CreateWorkspace  {
    /**
     * 
     * @type {string}
     * @memberof CreateWorkspace
     */
    name: string;
}

export function CreateWorkspaceFromJSON(json: any): CreateWorkspace {
    return {
        'name': json['name'],
    };
}

export function CreateWorkspaceToJSON(value?: CreateWorkspace): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'name': value.name,
    };
}


