// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum DataClearance {
    own_institution = 'own-institution',
    cross_institution = 'cross-institution',
    all = 'all'
}

export function DataClearanceFromJSON(json: any): DataClearance {
    return json as DataClearance;
}

export function DataClearanceToJSON(value?: DataClearance): any {
    return value as any;
}

