// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DateRange
 */
export interface DateRange  {
    /**
     * 
     * @type {Date}
     * @memberof DateRange
     */
    min?: Date;
    /**
     * 
     * @type {Date}
     * @memberof DateRange
     */
    max?: Date;
}

export function DateRangeFromJSON(json: any): DateRange {
    return {
        'min': !exists(json, 'min') ? undefined : new Date(json['min']),
        'max': !exists(json, 'max') ? undefined : new Date(json['max']),
    };
}

export function DateRangeToJSON(value?: DateRange): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'min': value.min === undefined ? undefined : value.min.toISOString(),
        'max': value.max === undefined ? undefined : value.max.toISOString(),
    };
}


