// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DateRange,
    DateRangeFromJSON,
    DateRangeToJSON,
} from './';

/**
 * 
 * @export
 * @interface FilterOptions
 */
export interface FilterOptions  {
    /**
     * 
     * @type {DateRange}
     * @memberof FilterOptions
     */
    date_sample?: DateRange;
    /**
     * 
     * @type {DateRange}
     * @memberof FilterOptions
     */
    date_received?: DateRange;
    /**
     * 
     * @type {Array<string>}
     * @memberof FilterOptions
     */
    institutions?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof FilterOptions
     */
    project_titles?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof FilterOptions
     */
    project_numbers?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof FilterOptions
     */
    animals?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof FilterOptions
     */
    run_ids?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof FilterOptions
     */
    isolate_ids?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof FilterOptions
     */
    fud_nos?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof FilterOptions
     */
    cluster_ids?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof FilterOptions
     */
    qc_provided_species?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof FilterOptions
     */
    serotype_finals?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof FilterOptions
     */
    st_finals?: Array<string>;
}

export function FilterOptionsFromJSON(json: any): FilterOptions {
    return {
        'date_sample': !exists(json, 'date_sample') ? undefined : DateRangeFromJSON(json['date_sample']),
        'date_received': !exists(json, 'date_received') ? undefined : DateRangeFromJSON(json['date_received']),
        'institutions': !exists(json, 'institutions') ? undefined : json['institutions'],
        'project_titles': !exists(json, 'project_titles') ? undefined : json['project_titles'],
        'project_numbers': !exists(json, 'project_numbers') ? undefined : json['project_numbers'],
        'animals': !exists(json, 'animals') ? undefined : json['animals'],
        'run_ids': !exists(json, 'run_ids') ? undefined : json['run_ids'],
        'isolate_ids': !exists(json, 'isolate_ids') ? undefined : json['isolate_ids'],
        'fud_nos': !exists(json, 'fud_nos') ? undefined : json['fud_nos'],
        'cluster_ids': !exists(json, 'cluster_ids') ? undefined : json['cluster_ids'],
        'qc_provided_species': !exists(json, 'qc_provided_species') ? undefined : json['qc_provided_species'],
        'serotype_finals': !exists(json, 'serotype_finals') ? undefined : json['serotype_finals'],
        'st_finals': !exists(json, 'st_finals') ? undefined : json['st_finals'],
    };
}

export function FilterOptionsToJSON(value?: FilterOptions): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'date_sample': DateRangeToJSON(value.date_sample),
        'date_received': DateRangeToJSON(value.date_received),
        'institutions': value.institutions,
        'project_titles': value.project_titles,
        'project_numbers': value.project_numbers,
        'animals': value.animals,
        'run_ids': value.run_ids,
        'isolate_ids': value.isolate_ids,
        'fud_nos': value.fud_nos,
        'cluster_ids': value.cluster_ids,
        'qc_provided_species': value.qc_provided_species,
        'serotype_finals': value.serotype_finals,
        'st_finals': value.st_finals,
    };
}


