// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineObject
 */
export interface InlineObject  {
    /**
     * 
     * @type {boolean}
     * @memberof InlineObject
     */
    isFavorite: boolean;
}

export function InlineObjectFromJSON(json: any): InlineObject {
    return {
        'isFavorite': json['isFavorite'],
    };
}

export function InlineObjectToJSON(value?: InlineObject): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'isFavorite': value.isFavorite,
    };
}


