// tslint:disable
/**
 * SAP
 * Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Organization,
    OrganizationFromJSON,
    OrganizationToJSON,
} from './';

/**
 * 
 * @export
 * @interface MetadataReloadRequest
 */
export interface MetadataReloadRequest  {
    /**
     * 
     * @type {string}
     * @memberof MetadataReloadRequest
     */
    isolateId?: string;
    /**
     * 
     * @type {Organization}
     * @memberof MetadataReloadRequest
     */
    institution?: Organization;
}

export function MetadataReloadRequestFromJSON(json: any): MetadataReloadRequest {
    return {
        'isolateId': !exists(json, 'isolateId') ? undefined : json['isolateId'],
        'institution': !exists(json, 'institution') ? undefined : OrganizationFromJSON(json['institution']),
    };
}

export function MetadataReloadRequestToJSON(value?: MetadataReloadRequest): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'isolateId': value.isolateId,
        'institution': OrganizationToJSON(value.institution),
    };
}


