// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MicroreactUrlResponse
 */
export interface MicroreactUrlResponse  {
    /**
     * 
     * @type {string}
     * @memberof MicroreactUrlResponse
     */
    url?: string;
}

export function MicroreactUrlResponseFromJSON(json: any): MicroreactUrlResponse {
    return {
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function MicroreactUrlResponseToJSON(value?: MicroreactUrlResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'url': value.url,
    };
}


