// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MicroreactProject
 */
export interface MicroreactProject  {
    /**
     * 
     * @type {string}
     * @memberof MicroreactProject
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof MicroreactProject
     */
    url?: string;
}

export function MicroreactProjectFromJSON(json: any): MicroreactProject {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function MicroreactProjectToJSON(value?: MicroreactProject): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'url': value.url,
    };
}


