// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Parameters for a REST request for a nearest neighbors calculation.
 * @export
 * @interface NearestNeighborsRequest
 */
export interface NearestNeighborsRequest  {
    /**
     * 
     * @type {string}
     * @memberof NearestNeighborsRequest
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof NearestNeighborsRequest
     */
    cutoff: number;
}

export function NearestNeighborsRequestFromJSON(json: any): NearestNeighborsRequest {
    return {
        'id': json['id'],
        'cutoff': json['cutoff'],
    };
}

export function NearestNeighborsRequestToJSON(value?: NearestNeighborsRequest): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'cutoff': value.cutoff,
    };
}


