// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewickTreeResponse
 */
export interface NewickTreeResponse  {
    /**
     * 
     * @type {string}
     * @memberof NewickTreeResponse
     */
    tree: string;
}

export function NewickTreeResponseFromJSON(json: any): NewickTreeResponse {
    return {
        'tree': json['tree'],
    };
}

export function NewickTreeResponseToJSON(value?: NewickTreeResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'tree': value.tree,
    };
}


