// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewMicroreactProjectResponse
 */
export interface NewMicroreactProjectResponse  {
    /**
     * 
     * @type {boolean}
     * @memberof NewMicroreactProjectResponse
     */
    isOwner?: boolean;
    /**
     * 
     * @type {string}
     * @memberof NewMicroreactProjectResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof NewMicroreactProjectResponse
     */
    url?: string;
}

export function NewMicroreactProjectResponseFromJSON(json: any): NewMicroreactProjectResponse {
    return {
        'isOwner': !exists(json, 'isOwner') ? undefined : json['isOwner'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function NewMicroreactProjectResponseToJSON(value?: NewMicroreactProjectResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'isOwner': value.isOwner,
        'id': value.id,
        'url': value.url,
    };
}


