// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TreeMethod,
    TreeMethodFromJSON,
    TreeMethodToJSON,
} from './';

/**
 * 
 * @export
 * @interface NewMicroreactProjectRequest
 */
export interface NewMicroreactProjectRequest  {
    /**
     * 
     * @type {string}
     * @memberof NewMicroreactProjectRequest
     */
    workspace: string;
    /**
     * 
     * @type {string}
     * @memberof NewMicroreactProjectRequest
     */
    mr_access_token: string;
    /**
     * 
     * @type {TreeMethod}
     * @memberof NewMicroreactProjectRequest
     */
    tree_method: TreeMethod;
}

export function NewMicroreactProjectRequestFromJSON(json: any): NewMicroreactProjectRequest {
    return {
        'workspace': json['workspace'],
        'mr_access_token': json['mr_access_token'],
        'tree_method': TreeMethodFromJSON(json['tree_method']),
    };
}

export function NewMicroreactProjectRequestToJSON(value?: NewMicroreactProjectRequest): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'workspace': value.workspace,
        'mr_access_token': value.mr_access_token,
        'tree_method': TreeMethodToJSON(value.tree_method),
    };
}


