// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TreeCalc,
    TreeCalcFromJSON,
    TreeCalcToJSON,
} from './';

/**
 * 
 * @export
 * @interface NewMicroreactProjectRequest
 */
export interface NewMicroreactProjectRequest  {
    /**
     * 
     * @type {string}
     * @memberof NewMicroreactProjectRequest
     */
    project_name: string;
    /**
     * 
     * @type {Array<TreeCalc>}
     * @memberof NewMicroreactProjectRequest
     */
    tree_calcs: Array<TreeCalc>;
    /**
     * 
     * @type {Array<string>}
     * @memberof NewMicroreactProjectRequest
     */
    metadata_keys: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof NewMicroreactProjectRequest
     */
    metadata_values: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof NewMicroreactProjectRequest
     */
    mr_access_token: string;
    /**
     * 
     * @type {string}
     * @memberof NewMicroreactProjectRequest
     */
    mr_base_url: string;
    /**
     * 
     * @type {boolean}
     * @memberof NewMicroreactProjectRequest
     */
    _public?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof NewMicroreactProjectRequest
     */
    verify?: boolean;
}

export function NewMicroreactProjectRequestFromJSON(json: any): NewMicroreactProjectRequest {
    return {
        'project_name': json['project_name'],
        'tree_calcs': (json['tree_calcs'] as Array<any>).map(TreeCalcFromJSON),
        'metadata_keys': json['metadata_keys'],
        'metadata_values': json['metadata_values'],
        'mr_access_token': json['mr_access_token'],
        'mr_base_url': json['mr_base_url'],
        '_public': !exists(json, 'public') ? undefined : json['public'],
        'verify': !exists(json, 'verify') ? undefined : json['verify'],
    };
}

export function NewMicroreactProjectRequestToJSON(value?: NewMicroreactProjectRequest): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'project_name': value.project_name,
        'tree_calcs': (value.tree_calcs as Array<any>).map(TreeCalcToJSON),
        'metadata_keys': value.metadata_keys,
        'metadata_values': value.metadata_values,
        'mr_access_token': value.mr_access_token,
        'mr_base_url': value.mr_base_url,
        'public': value._public,
        'verify': value.verify,
    };
}


