// tslint:disable
/**
 * SAP
 * Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    QueryExpression,
    QueryExpressionFromJSON,
    QueryExpressionToJSON,
    QueryLeaf,
    QueryLeafFromJSON,
    QueryLeafToJSON,
} from './';

/**
 * @type Operand
 * @export
 */
export type Operand = QueryExpression | QueryLeaf;


export function OperandFromJSON(json: any): Operand {
  switch (json.operator) {
  case 'AND': return QueryExpressionFromJSON(json);
  case 'AND NOT': return QueryExpressionFromJSON(json);
  case 'OR': return QueryExpressionFromJSON(json);
  case 'OR NOT': return QueryExpressionFromJSON(json);
  case 'TERM': return QueryLeafFromJSON(json);
  default: throw new Error("Unexpected operator value.");
  }
}

export function OperandToJSON(value?: Operand): any {
    if (value === undefined) {
        return undefined;
    }

    switch (value.operator) {
    case 'AND': return QueryExpressionToJSON(<QueryExpression>value);
    case 'AND NOT': return QueryExpressionToJSON(<QueryExpression>value);
    case 'OR': return QueryExpressionToJSON(<QueryExpression>value);
    case 'OR NOT': return QueryExpressionToJSON(<QueryExpression>value);
    case 'TERM': return QueryLeafToJSON(<QueryLeaf>value);
    default: throw new Error("Unexpected operator value.");
    }
}

