// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AnalysisResult,
    AnalysisResultFromJSON,
    AnalysisResultToJSON,
    ApprovalStatus,
    ApprovalStatusFromJSON,
    ApprovalStatusToJSON,
    FilterOptions,
    FilterOptionsFromJSON,
    FilterOptionsToJSON,
} from './';

/**
 * 
 * @export
 * @interface PageOfAnalysis
 */
export interface PageOfAnalysis  {
    /**
     * 
     * @type {string}
     * @memberof PageOfAnalysis
     */
    paging_token: string;
    /**
     * 
     * @type {number}
     * @memberof PageOfAnalysis
     */
    total_count: number;
    /**
     * 
     * @type {Array<AnalysisResult>}
     * @memberof PageOfAnalysis
     */
    items: Array<AnalysisResult>;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: ApprovalStatus; }; }}
     * @memberof PageOfAnalysis
     */
    approval_matrix: { [key: string]: { [key: string]: ApprovalStatus; }; };
    /**
     * 
     * @type {FilterOptions}
     * @memberof PageOfAnalysis
     */
    filter_options: FilterOptions;
}

export function PageOfAnalysisFromJSON(json: any): PageOfAnalysis {
    return {
        'paging_token': json['paging_token'],
        'total_count': json['total_count'],
        'items': (json['items'] as Array<any>).map(AnalysisResultFromJSON),
        'approval_matrix': json['approval_matrix'],
        'filter_options': FilterOptionsFromJSON(json['filter_options']),
    };
}

export function PageOfAnalysisToJSON(value?: PageOfAnalysis): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'paging_token': value.paging_token,
        'total_count': value.total_count,
        'items': (value.items as Array<any>).map(AnalysisResultToJSON),
        'approval_matrix': value.approval_matrix,
        'filter_options': FilterOptionsToJSON(value.filter_options),
    };
}


