// tslint:disable
/**
 * SAP
 * Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  AnalysisResult,
  AnalysisResultFromJSON,
  AnalysisResultToJSON,
} from "./";

/**
 *
 * @export
 * @interface PageOfAnalysis
 */
export interface PageOfAnalysis {
  /**
   *
   * @type {string}
   * @memberof PageOfAnalysis
   */
  pagingToken: string;
  /**
   *
   * @type {number}
   * @memberof PageOfAnalysis
   */
  totalCount: number;
  /**
   *
   * @type {Array<AnalysisResult>}
   * @memberof PageOfAnalysis
   */
  items: Array<AnalysisResult>;
}

export function PageOfAnalysisFromJSON(json: any): PageOfAnalysis {
  return {
    pagingToken: json["pagingToken"],
    totalCount: json["totalCount"],
    items: (json["items"] as Array<any>).map(AnalysisResultFromJSON),
  };
}

export function PageOfAnalysisToJSON(value?: PageOfAnalysis): any {
  if (value === undefined) {
    return undefined;
  }
  return {
    pagingToken: value.pagingToken,
    totalCount: value.totalCount,
    items: (value.items as Array<any>).map(AnalysisResultToJSON),
  };
}
