// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Gene,
    GeneFromJSON,
    GeneToJSON,
} from './';

/**
 * 
 * @export
 * @interface Phenotype
 */
export interface Phenotype  {
    /**
     * 
     * @type {Array<string>}
     * @memberof Phenotype
     */
    amr_classes?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: Gene; }}
     * @memberof Phenotype
     */
    genes?: { [key: string]: Gene; };
}

export function PhenotypeFromJSON(json: any): Phenotype {
    return {
        'amr_classes': !exists(json, 'amr_classes') ? undefined : json['amr_classes'],
        'genes': !exists(json, 'genes') ? undefined : mapValues(json['genes'], GeneFromJSON),
    };
}

export function PhenotypeToJSON(value?: Phenotype): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'amr_classes': value.amr_classes,
        'genes': value.genes === undefined ? undefined : mapValues(value.genes, GeneToJSON),
    };
}


