// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Project
 */
export interface Project  {
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    project_key?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Project
     */
    _private?: boolean;
}

export function ProjectFromJSON(json: any): Project {
    return {
        'project_key': !exists(json, 'project_key') ? undefined : json['project_key'],
        '_private': !exists(json, 'private') ? undefined : json['private'],
    };
}

export function ProjectToJSON(value?: Project): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'project_key': value.project_key,
        'private': value._private,
    };
}


