// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Project
 */
export interface Project  {
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    project_key: string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    project_title?: string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    project_number?: string;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    count: number;
    /**
     * 
     * @type {boolean}
     * @memberof Project
     */
    is_private: boolean;
}

export function ProjectFromJSON(json: any): Project {
    return {
        'project_key': json['project_key'],
        'project_title': !exists(json, 'project_title') ? undefined : json['project_title'],
        'project_number': !exists(json, 'project_number') ? undefined : json['project_number'],
        'count': json['count'],
        'is_private': json['is_private'],
    };
}

export function ProjectToJSON(value?: Project): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'project_key': value.project_key,
        'project_title': value.project_title,
        'project_number': value.project_number,
        'count': value.count,
        'is_private': value.is_private,
    };
}


