// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum QueryOperator {
    AND = 'AND',
    OR = 'OR',
    AND_NOT = 'AND NOT',
    OR_NOT = 'OR NOT',
    implicit = '<implicit>'
}

export function QueryOperatorFromJSON(json: any): QueryOperator {
    return json as QueryOperator;
}

export function QueryOperatorToJSON(value?: QueryOperator): any {
    return value as any;
}

