// tslint:disable
/**
 * SAP
 * Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Operand,
    OperandFromJSON,
    OperandToJSON,
} from './';

/**
 * 
 * @export
 * @interface QueryExpression
 */
export interface QueryExpression  {
    /**
     * 
     * @type {Operand}
     * @memberof QueryExpression
     */
    left?: Operand;
    /**
     * 
     * @type {string}
     * @memberof QueryExpression
     */
    operator?: QueryExpressionOperatorEnum;
    /**
     * 
     * @type {Operand}
     * @memberof QueryExpression
     */
    right?: Operand;
}

export function QueryExpressionFromJSON(json: any): QueryExpression {
    return {
        'left': !exists(json, 'left') ? undefined : json['left'],
        'operator': !exists(json, 'operator') ? undefined : json['operator'],
        'right': !exists(json, 'right') ? undefined : json['right'],
    };
}

export function QueryExpressionToJSON(value?: QueryExpression): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'left': value.left,
        'operator': value.operator,
        'right': value.right,
    };
}

/**
* @export
* @enum {string}
*/
export enum QueryExpressionOperatorEnum {
    AND = 'AND',
    OR = 'OR',
    AND_NOT = 'AND NOT',
    OR_NOT = 'OR NOT',
    implicit = '<implicit>'
}


