// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum QueryRangeInclusivity {
    left = 'left',
    right = 'right',
    both = 'both',
    none = 'none'
}

export function QueryRangeInclusivityFromJSON(json: any): QueryRangeInclusivity {
    return json as QueryRangeInclusivity;
}

export function QueryRangeInclusivityToJSON(value?: QueryRangeInclusivity): any {
    return value as any;
}

