// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SampleCategoriesResistanceReport,
    SampleCategoriesResistanceReportFromJSON,
    SampleCategoriesResistanceReportToJSON,
} from './';

/**
 * 
 * @export
 * @interface SampleCategoriesResistance
 */
export interface SampleCategoriesResistance  {
    /**
     * 
     * @type {string}
     * @memberof SampleCategoriesResistance
     */
    summary?: string;
    /**
     * 
     * @type {SampleCategoriesResistanceReport}
     * @memberof SampleCategoriesResistance
     */
    report?: SampleCategoriesResistanceReport;
}

export function SampleCategoriesResistanceFromJSON(json: any): SampleCategoriesResistance {
    return {
        'summary': !exists(json, 'summary') ? undefined : json['summary'],
        'report': !exists(json, 'report') ? undefined : SampleCategoriesResistanceReportFromJSON(json['report']),
    };
}

export function SampleCategoriesResistanceToJSON(value?: SampleCategoriesResistance): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'summary': value.summary,
        'report': SampleCategoriesResistanceReportToJSON(value.report),
    };
}


