// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Phenotype,
    PhenotypeFromJSON,
    PhenotypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface SampleCategoriesResistanceReport
 */
export interface SampleCategoriesResistanceReport  {
    /**
     * 
     * @type {{ [key: string]: Phenotype; }}
     * @memberof SampleCategoriesResistanceReport
     */
    phenotypes?: { [key: string]: Phenotype; };
}

export function SampleCategoriesResistanceReportFromJSON(json: any): SampleCategoriesResistanceReport {
    return {
        'phenotypes': !exists(json, 'phenotypes') ? undefined : mapValues(json['phenotypes'], PhenotypeFromJSON),
    };
}

export function SampleCategoriesResistanceReportToJSON(value?: SampleCategoriesResistanceReport): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'phenotypes': value.phenotypes === undefined ? undefined : mapValues(value.phenotypes, PhenotypeToJSON),
    };
}


