// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SampleCategoriesResistance,
    SampleCategoriesResistanceFromJSON,
    SampleCategoriesResistanceToJSON,
} from './';

/**
 * 
 * @export
 * @interface SampleCategories
 */
export interface SampleCategories  {
    /**
     * 
     * @type {SampleCategoriesResistance}
     * @memberof SampleCategories
     */
    resistance?: SampleCategoriesResistance;
}

export function SampleCategoriesFromJSON(json: any): SampleCategories {
    return {
        'resistance': !exists(json, 'resistance') ? undefined : SampleCategoriesResistanceFromJSON(json['resistance']),
    };
}

export function SampleCategoriesToJSON(value?: SampleCategories): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'resistance': SampleCategoriesResistanceToJSON(value.resistance),
    };
}


