// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SampleCategories,
    SampleCategoriesFromJSON,
    SampleCategoriesToJSON,
} from './';

/**
 * 
 * @export
 * @interface Sample
 */
export interface Sample  {
    /**
     * 
     * @type {string}
     * @memberof Sample
     */
    name?: string;
    /**
     * 
     * @type {SampleCategories}
     * @memberof Sample
     */
    categories?: SampleCategories;
}

export function SampleFromJSON(json: any): Sample {
    return {
        'name': !exists(json, 'name') ? undefined : json['name'],
        'categories': !exists(json, 'categories') ? undefined : SampleCategoriesFromJSON(json['categories']),
    };
}

export function SampleToJSON(value?: Sample): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'name': value.name,
        'categories': SampleCategoriesToJSON(value.categories),
    };
}


