// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetFavorite
 */
export interface SetFavorite  {
    /**
     * 
     * @type {string}
     * @memberof SetFavorite
     */
    workspaceId: string;
    /**
     * 
     * @type {boolean}
     * @memberof SetFavorite
     */
    isFavorite: boolean;
}

export function SetFavoriteFromJSON(json: any): SetFavorite {
    return {
        'workspaceId': json['workspaceId'],
        'isFavorite': json['isFavorite'],
    };
}

export function SetFavoriteToJSON(value?: SetFavorite): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'workspaceId': value.workspaceId,
        'isFavorite': value.isFavorite,
    };
}


