// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetWsTag
 */
export interface SetWsTag  {
    /**
     * 
     * @type {string}
     * @memberof SetWsTag
     */
    workspaceId: string;
    /**
     * 
     * @type {string}
     * @memberof SetWsTag
     */
    tag: string;
    /**
     * true -> Adds tag to workspace. false -> remove tag from workspace
     * @type {boolean}
     * @memberof SetWsTag
     */
    addOrRemove: boolean;
}

export function SetWsTagFromJSON(json: any): SetWsTag {
    return {
        'workspaceId': json['workspaceId'],
        'tag': json['tag'],
        'addOrRemove': json['addOrRemove'],
    };
}

export function SetWsTagToJSON(value?: SetWsTag): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'workspaceId': value.workspaceId,
        'tag': value.tag,
        'addOrRemove': value.addOrRemove,
    };
}


