// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BaseMetadata,
    BaseMetadataFromJSON,
    BaseMetadataToJSON,
} from './';

/**
 * 
 * @export
 * @interface SingleUploadRequest
 */
export interface SingleUploadRequest  {
    /**
     * 
     * @type {BaseMetadata}
     * @memberof SingleUploadRequest
     */
    metadata: BaseMetadata;
    /**
     * 
     * @type {Blob}
     * @memberof SingleUploadRequest
     */
    file: Blob;
}

export function SingleUploadRequestFromJSON(json: any): SingleUploadRequest {
    return {
        'metadata': BaseMetadataFromJSON(json['metadata']),
        'file': json['file'],
    };
}

export function SingleUploadRequestToJSON(value?: SingleUploadRequest): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'metadata': BaseMetadataToJSON(value.metadata),
        'file': value.file,
    };
}


