// tslint:disable
/**
 * SAP
 * Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    BaseMetadata,
    BaseMetadataFromJSON,
    BaseMetadataToJSON,
    Organization,
    OrganizationFromJSON,
    OrganizationToJSON,
    TbrSpecificMetadata,
    TbrSpecificMetadataFromJSON,
    TbrSpecificMetadataToJSON,
} from './';

/**
 * @type TbrMetadata
 * @export
 */
export interface TbrMetadata extends BaseMetadata, TbrSpecificMetadata {
}

export function TbrMetadataFromJSON(json: any): TbrMetadata {
    return {
        ...BaseMetadataFromJSON(json),
        ...TbrSpecificMetadataFromJSON(json),
    };
}

export function TbrMetadataToJSON(value?: TbrMetadata): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        ...BaseMetadataToJSON(value),
        ...TbrSpecificMetadataToJSON(value),
    };
}
