// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TbrSpecificMetadata
 */
export interface TbrSpecificMetadata  {
    /**
     * 
     * @type {string}
     * @memberof TbrSpecificMetadata
     */
    cpr_nr?: string;
    /**
     * 
     * @type {string}
     * @memberof TbrSpecificMetadata
     */
    gender?: TbrSpecificMetadataGenderEnum;
    /**
     * 
     * @type {string}
     * @memberof TbrSpecificMetadata
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof TbrSpecificMetadata
     */
    age?: number;
    /**
     * 
     * @type {string}
     * @memberof TbrSpecificMetadata
     */
    travel?: string;
    /**
     * 
     * @type {string}
     * @memberof TbrSpecificMetadata
     */
    travel_country?: string;
    /**
     * 
     * @type {Date}
     * @memberof TbrSpecificMetadata
     */
    run_date: Date;
    /**
     * 
     * @type {Date}
     * @memberof TbrSpecificMetadata
     */
    kma_received_date?: Date;
    /**
     * 
     * @type {string}
     * @memberof TbrSpecificMetadata
     */
    kma?: string;
    /**
     * 
     * @type {string}
     * @memberof TbrSpecificMetadata
     */
    region?: string;
    /**
     * 
     * @type {string}
     * @memberof TbrSpecificMetadata
     */
    fud_number?: string;
    /**
     * 
     * @type {string}
     * @memberof TbrSpecificMetadata
     */
    cluster_id?: string;
    /**
     * 
     * @type {string}
     * @memberof TbrSpecificMetadata
     */
    epi_export?: string;
}

export function TbrSpecificMetadataFromJSON(json: any): TbrSpecificMetadata {
    return {
        'cpr_nr': !exists(json, 'cpr_nr') ? undefined : json['cpr_nr'],
        'gender': !exists(json, 'gender') ? undefined : json['gender'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'age': !exists(json, 'age') ? undefined : json['age'],
        'travel': !exists(json, 'travel') ? undefined : json['travel'],
        'travel_country': !exists(json, 'travel_country') ? undefined : json['travel_country'],
        'run_date': new Date(json['run_date']),
        'kma_received_date': !exists(json, 'kma_received_date') ? undefined : new Date(json['kma_received_date']),
        'kma': !exists(json, 'kma') ? undefined : json['kma'],
        'region': !exists(json, 'region') ? undefined : json['region'],
        'fud_number': !exists(json, 'fud_number') ? undefined : json['fud_number'],
        'cluster_id': !exists(json, 'cluster_id') ? undefined : json['cluster_id'],
        'epi_export': !exists(json, 'epi_export') ? undefined : json['epi_export'],
    };
}

export function TbrSpecificMetadataToJSON(value?: TbrSpecificMetadata): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'cpr_nr': value.cpr_nr,
        'gender': value.gender,
        'name': value.name,
        'age': value.age,
        'travel': value.travel,
        'travel_country': value.travel_country,
        'run_date': value.run_date.toISOString(),
        'kma_received_date': value.kma_received_date === undefined ? undefined : value.kma_received_date.toISOString(),
        'kma': value.kma,
        'region': value.region,
        'fud_number': value.fud_number,
        'cluster_id': value.cluster_id,
        'epi_export': value.epi_export,
    };
}

/**
* @export
* @enum {string}
*/
export enum TbrSpecificMetadataGenderEnum {
    M = 'M',
    K = 'K'
}


