// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TreeCalc
 */
export interface TreeCalc  {
    /**
     * 
     * @type {string}
     * @memberof TreeCalc
     */
    method: string;
    /**
     * 
     * @type {string}
     * @memberof TreeCalc
     */
    result: string;
}

export function TreeCalcFromJSON(json: any): TreeCalc {
    return {
        'method': json['method'],
        'result': json['result'],
    };
}

export function TreeCalcToJSON(value?: TreeCalc): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'method': value.method,
        'result': value.result,
    };
}


