// tslint:disable
/**
 * SAP
 * Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadResponse
 */
export interface UploadResponse  {
    /**
     * 
     * @type {Array<string>}
     * @memberof UploadResponse
     */
    errors?: Array<string>;
}

export function UploadResponseFromJSON(json: any): UploadResponse {
    return {
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
    };
}

export function UploadResponseToJSON(value?: UploadResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'errors': value.errors,
    };
}


