// tslint:disable
/**
 * SAP
 * Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadErrorResponse
 */
export interface UploadErrorResponse  {
    /**
     * 
     * @type {string}
     * @memberof UploadErrorResponse
     */
    isolate_id?: string;
    /**
     * 
     * @type {string}
     * @memberof UploadErrorResponse
     */
    error?: string;
}

export function UploadErrorResponseFromJSON(json: any): UploadErrorResponse {
    return {
        'isolate_id': !exists(json, 'isolate_id') ? undefined : json['isolate_id'],
        'error': !exists(json, 'error') ? undefined : json['error'],
    };
}

export function UploadErrorResponseToJSON(value?: UploadErrorResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'isolate_id': value.isolate_id,
        'error': value.error,
    };
}


