// tslint:disable
/**
 * SAP
 * Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UploadResponseError,
    UploadResponseErrorFromJSON,
    UploadResponseErrorToJSON,
} from './';

/**
 * 
 * @export
 * @interface UploadResponse
 */
export interface UploadResponse  {
    /**
     * 
     * @type {UploadResponseError}
     * @memberof UploadResponse
     */
    error?: UploadResponseError;
}

export function UploadResponseFromJSON(json: any): UploadResponse {
    return {
        'error': !exists(json, 'error') ? undefined : UploadResponseErrorFromJSON(json['error']),
    };
}

export function UploadResponseToJSON(value?: UploadResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'error': UploadResponseErrorToJSON(value.error),
    };
}


