// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Corresponds to fields of the metadata.tsv file for initiating an execution of the analysis tool pipeline
 * @export
 * @interface UploadMetadataFields
 */
export interface UploadMetadataFields  {
    /**
     * 
     * @type {string}
     * @memberof UploadMetadataFields
     */
    sample_id?: string;
    /**
     * 
     * @type {string}
     * @memberof UploadMetadataFields
     */
    provided_species?: string;
    /**
     * 
     * @type {string}
     * @memberof UploadMetadataFields
     */
    group?: string;
    /**
     * 
     * @type {string}
     * @memberof UploadMetadataFields
     */
    experiment_name?: string;
    /**
     * 
     * @type {Date}
     * @memberof UploadMetadataFields
     */
    sequence_run_date?: Date;
    /**
     * 
     * @type {string}
     * @memberof UploadMetadataFields
     */
    sofi_sequence_id?: string;
    /**
     * 
     * @type {string}
     * @memberof UploadMetadataFields
     */
    project_no?: string;
    /**
     * 
     * @type {string}
     * @memberof UploadMetadataFields
     */
    project_title?: string;
}

export function UploadMetadataFieldsFromJSON(json: any): UploadMetadataFields {
    return {
        'sample_id': !exists(json, 'sample_id') ? undefined : json['sample_id'],
        'provided_species': !exists(json, 'provided_species') ? undefined : json['provided_species'],
        'group': !exists(json, 'group') ? undefined : json['group'],
        'experiment_name': !exists(json, 'experiment_name') ? undefined : json['experiment_name'],
        'sequence_run_date': !exists(json, 'sequence_run_date') ? undefined : new Date(json['sequence_run_date']),
        'sofi_sequence_id': !exists(json, 'sofi_sequence_id') ? undefined : json['sofi_sequence_id'],
        'project_no': !exists(json, 'project_no') ? undefined : json['project_no'],
        'project_title': !exists(json, 'project_title') ? undefined : json['project_title'],
    };
}

export function UploadMetadataFieldsToJSON(value?: UploadMetadataFields): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'sample_id': value.sample_id,
        'provided_species': value.provided_species,
        'group': value.group,
        'experiment_name': value.experiment_name,
        'sequence_run_date': value.sequence_run_date === undefined ? undefined : value.sequence_run_date.toISOString(),
        'sofi_sequence_id': value.sofi_sequence_id,
        'project_no': value.project_no,
        'project_title': value.project_title,
    };
}


