// tslint:disable
/**
 * SAP
 * Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserDefinedViewTableState,
    UserDefinedViewTableStateFromJSON,
    UserDefinedViewTableStateToJSON,
} from './';

/**
 * 
 * @export
 * @interface UserDefinedView
 */
export interface UserDefinedView  {
    /**
     * 
     * @type {string}
     * @memberof UserDefinedView
     */
    name?: string;
    /**
     * 
     * @type {UserDefinedViewTableState}
     * @memberof UserDefinedView
     */
    tableState?: UserDefinedViewTableState;
}

export function UserDefinedViewFromJSON(json: any): UserDefinedView {
    return {
        'name': !exists(json, 'name') ? undefined : json['name'],
        'tableState': !exists(json, 'tableState') ? undefined : UserDefinedViewTableStateFromJSON(json['tableState']),
    };
}

export function UserDefinedViewToJSON(value?: UserDefinedView): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'name': value.name,
        'tableState': UserDefinedViewTableStateToJSON(value.tableState),
    };
}


