// tslint:disable
/**
 * SAP
 * Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Null,
    NullFromJSON,
    NullToJSON,
} from './';

/**
 * 
 * @export
 * @interface UserDefinedViewTableStateColumnResizing
 */
export interface UserDefinedViewTableStateColumnResizing  {
    /**
     * 
     * @type {object}
     * @memberof UserDefinedViewTableStateColumnResizing
     */
    columnWidths?: object;
    /**
     * 
     * @type {number}
     * @memberof UserDefinedViewTableStateColumnResizing
     */
    columnWidth?: number;
    /**
     * 
     * @type {Array<Array<object>>}
     * @memberof UserDefinedViewTableStateColumnResizing
     */
    headerIdWidths?: Array<Array<object>>;
    /**
     * 
     * @type {boolean}
     * @memberof UserDefinedViewTableStateColumnResizing
     */
    isResizingColumn?: boolean;
    /**
     * 
     * @type {Null}
     * @memberof UserDefinedViewTableStateColumnResizing
     */
    startX?: Null;
}

export function UserDefinedViewTableStateColumnResizingFromJSON(json: any): UserDefinedViewTableStateColumnResizing {
    return {
        'columnWidths': !exists(json, 'columnWidths') ? undefined : json['columnWidths'],
        'columnWidth': !exists(json, 'columnWidth') ? undefined : json['columnWidth'],
        'headerIdWidths': !exists(json, 'headerIdWidths') ? undefined : json['headerIdWidths'],
        'isResizingColumn': !exists(json, 'isResizingColumn') ? undefined : json['isResizingColumn'],
        'startX': !exists(json, 'startX') ? undefined : NullFromJSON(json['startX']),
    };
}

export function UserDefinedViewTableStateColumnResizingToJSON(value?: UserDefinedViewTableStateColumnResizing): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'columnWidths': value.columnWidths,
        'columnWidth': value.columnWidth,
        'headerIdWidths': value.headerIdWidths,
        'isResizingColumn': value.isResizingColumn,
        'startX': NullToJSON(value.startX),
    };
}


