// tslint:disable
/**
 * SAP
 * Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDefinedViewColumnResizingColumnWidths
 */
export interface UserDefinedViewColumnResizingColumnWidths  {
    /**
     * 
     * @type {string}
     * @memberof UserDefinedViewColumnResizingColumnWidths
     */
    columnName?: string;
    /**
     * 
     * @type {number}
     * @memberof UserDefinedViewColumnResizingColumnWidths
     */
    width?: number;
}

export function UserDefinedViewColumnResizingColumnWidthsFromJSON(json: any): UserDefinedViewColumnResizingColumnWidths {
    return {
        'columnName': !exists(json, 'columnName') ? undefined : json['columnName'],
        'width': !exists(json, 'width') ? undefined : json['width'],
    };
}

export function UserDefinedViewColumnResizingColumnWidthsToJSON(value?: UserDefinedViewColumnResizingColumnWidths): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'columnName': value.columnName,
        'width': value.width,
    };
}


