// tslint:disable
/**
 * SAP
 * Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDefinedViewSortBy
 */
export interface UserDefinedViewSortBy  {
    /**
     * 
     * @type {boolean}
     * @memberof UserDefinedViewSortBy
     */
    desc?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserDefinedViewSortBy
     */
    id?: string;
}

export function UserDefinedViewSortByFromJSON(json: any): UserDefinedViewSortBy {
    return {
        'desc': !exists(json, 'desc') ? undefined : json['desc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function UserDefinedViewSortByToJSON(value?: UserDefinedViewSortBy): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'desc': value.desc,
        'id': value.id,
    };
}


