// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserDefinedViewColumnResizing,
    UserDefinedViewColumnResizingFromJSON,
    UserDefinedViewColumnResizingToJSON,
    UserDefinedViewSortBy,
    UserDefinedViewSortByFromJSON,
    UserDefinedViewSortByToJSON,
} from './';

/**
 * 
 * @export
 * @interface UserDefinedView
 */
export interface UserDefinedView  {
    /**
     * 
     * @type {string}
     * @memberof UserDefinedView
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserDefinedView
     */
    hidden_columns?: Array<string>;
    /**
     * 
     * @type {UserDefinedViewColumnResizing}
     * @memberof UserDefinedView
     */
    column_resizing?: UserDefinedViewColumnResizing;
    /**
     * 
     * @type {Array<UserDefinedViewSortBy>}
     * @memberof UserDefinedView
     */
    sort_by?: Array<UserDefinedViewSortBy>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserDefinedView
     */
    column_order?: Array<string>;
}

export function UserDefinedViewFromJSON(json: any): UserDefinedView {
    return {
        'name': !exists(json, 'name') ? undefined : json['name'],
        'hidden_columns': !exists(json, 'hidden_columns') ? undefined : json['hidden_columns'],
        'column_resizing': !exists(json, 'column_resizing') ? undefined : UserDefinedViewColumnResizingFromJSON(json['column_resizing']),
        'sort_by': !exists(json, 'sort_by') ? undefined : (json['sort_by'] as Array<any>).map(UserDefinedViewSortByFromJSON),
        'column_order': !exists(json, 'column_order') ? undefined : json['column_order'],
    };
}

export function UserDefinedViewToJSON(value?: UserDefinedView): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'name': value.name,
        'hidden_columns': value.hidden_columns,
        'column_resizing': UserDefinedViewColumnResizingToJSON(value.column_resizing),
        'sort_by': value.sort_by === undefined ? undefined : (value.sort_by as Array<any>).map(UserDefinedViewSortByToJSON),
        'column_order': value.column_order,
    };
}


