// tslint:disable
/**
 * SAP
 * Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserDefinedViewColumnResizing,
    UserDefinedViewColumnResizingFromJSON,
    UserDefinedViewColumnResizingToJSON,
    UserDefinedViewSortBy,
    UserDefinedViewSortByFromJSON,
    UserDefinedViewSortByToJSON,
} from './';

/**
 * 
 * @export
 * @interface UserDefinedView
 */
export interface UserDefinedView  {
    /**
     * 
     * @type {string}
     * @memberof UserDefinedView
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserDefinedView
     */
    hiddenColumns?: Array<string>;
    /**
     * 
     * @type {UserDefinedViewColumnResizing}
     * @memberof UserDefinedView
     */
    columnResizing?: UserDefinedViewColumnResizing;
    /**
     * 
     * @type {Array<UserDefinedViewSortBy>}
     * @memberof UserDefinedView
     */
    sortBy?: Array<UserDefinedViewSortBy>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserDefinedView
     */
    columnOrder?: Array<string>;
}

export function UserDefinedViewFromJSON(json: any): UserDefinedView {
    return {
        'name': !exists(json, 'name') ? undefined : json['name'],
        'hiddenColumns': !exists(json, 'hiddenColumns') ? undefined : json['hiddenColumns'],
        'columnResizing': !exists(json, 'columnResizing') ? undefined : UserDefinedViewColumnResizingFromJSON(json['columnResizing']),
        'sortBy': !exists(json, 'sortBy') ? undefined : (json['sortBy'] as Array<any>).map(UserDefinedViewSortByFromJSON),
        'columnOrder': !exists(json, 'columnOrder') ? undefined : json['columnOrder'],
    };
}

export function UserDefinedViewToJSON(value?: UserDefinedView): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'name': value.name,
        'hiddenColumns': value.hiddenColumns,
        'columnResizing': UserDefinedViewColumnResizingToJSON(value.columnResizing),
        'sortBy': value.sortBy === undefined ? undefined : (value.sortBy as Array<any>).map(UserDefinedViewSortByToJSON),
        'columnOrder': value.columnOrder,
    };
}


