// tslint:disable
/**
 * SAP
 * Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserDefinedViewColumnResizingColumnWidths,
    UserDefinedViewColumnResizingColumnWidthsFromJSON,
    UserDefinedViewColumnResizingColumnWidthsToJSON,
} from './';

/**
 * 
 * @export
 * @interface UserDefinedViewColumnResizing
 */
export interface UserDefinedViewColumnResizing  {
    /**
     * 
     * @type {Array<UserDefinedViewColumnResizingColumnWidths>}
     * @memberof UserDefinedViewColumnResizing
     */
    column_widths?: Array<UserDefinedViewColumnResizingColumnWidths>;
    /**
     * 
     * @type {number}
     * @memberof UserDefinedViewColumnResizing
     */
    column_width?: number;
}

export function UserDefinedViewColumnResizingFromJSON(json: any): UserDefinedViewColumnResizing {
    return {
        'column_widths': !exists(json, 'column_widths') ? undefined : (json['column_widths'] as Array<any>).map(UserDefinedViewColumnResizingColumnWidthsFromJSON),
        'column_width': !exists(json, 'column_width') ? undefined : json['column_width'],
    };
}

export function UserDefinedViewColumnResizingToJSON(value?: UserDefinedViewColumnResizing): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'column_widths': value.column_widths === undefined ? undefined : (value.column_widths as Array<any>).map(UserDefinedViewColumnResizingColumnWidthsToJSON),
        'column_width': value.column_width,
    };
}


