// tslint:disable
/**
 * SAP
 * Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserDefinedViewTableStateColumnResizing,
    UserDefinedViewTableStateColumnResizingFromJSON,
    UserDefinedViewTableStateColumnResizingToJSON,
    UserDefinedViewTableStateSortBy,
    UserDefinedViewTableStateSortByFromJSON,
    UserDefinedViewTableStateSortByToJSON,
} from './';

/**
 * 
 * @export
 * @interface UserDefinedViewTableState
 */
export interface UserDefinedViewTableState  {
    /**
     * 
     * @type {Array<string>}
     * @memberof UserDefinedViewTableState
     */
    hiddenColumns?: Array<string>;
    /**
     * 
     * @type {UserDefinedViewTableStateColumnResizing}
     * @memberof UserDefinedViewTableState
     */
    columnResizing?: UserDefinedViewTableStateColumnResizing;
    /**
     * 
     * @type {Array<UserDefinedViewTableStateSortBy>}
     * @memberof UserDefinedViewTableState
     */
    sortBy?: Array<UserDefinedViewTableStateSortBy>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserDefinedViewTableState
     */
    columnOrder?: Array<string>;
}

export function UserDefinedViewTableStateFromJSON(json: any): UserDefinedViewTableState {
    return {
        'hiddenColumns': !exists(json, 'hiddenColumns') ? undefined : json['hiddenColumns'],
        'columnResizing': !exists(json, 'columnResizing') ? undefined : UserDefinedViewTableStateColumnResizingFromJSON(json['columnResizing']),
        'sortBy': !exists(json, 'sortBy') ? undefined : (json['sortBy'] as Array<any>).map(UserDefinedViewTableStateSortByFromJSON),
        'columnOrder': !exists(json, 'columnOrder') ? undefined : json['columnOrder'],
    };
}

export function UserDefinedViewTableStateToJSON(value?: UserDefinedViewTableState): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'hiddenColumns': value.hiddenColumns,
        'columnResizing': UserDefinedViewTableStateColumnResizingToJSON(value.columnResizing),
        'sortBy': value.sortBy === undefined ? undefined : (value.sortBy as Array<any>).map(UserDefinedViewTableStateSortByToJSON),
        'columnOrder': value.columnOrder,
    };
}


