// tslint:disable
/**
 * SOFI
 * SOFI Sekvensanalyseplatform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkspaceInfo
 */
export interface WorkspaceInfo  {
    /**
     * 
     * @type {string}
     * @memberof WorkspaceInfo
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceInfo
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof WorkspaceInfo
     */
    samples: Array<string>;
}

export function WorkspaceInfoFromJSON(json: any): WorkspaceInfo {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'samples': json['samples'],
    };
}

export function WorkspaceInfoToJSON(value?: WorkspaceInfo): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'name': value.name,
        'samples': value.samples,
    };
}


